const REGISTRATION_ROSTER=[
  ...[['阿力','B'],['楷翔','B+C'],['懿宏','B+C'],['Duke','B'],['菜包','B'],['君','B'],['阿鴻','B'],['啟原','B+C'],['倫','B'],['純祥','B'],['Sherry','B'],['Mia','B'],['Sophia','B'],['Neil','B'],['丞毅','B'],['阿何','B']].map(([name,session])=>({name,session})),
  ...['欣寧','Elva','商商','政輝','Casper','Ariel','家瑋','羅強','Bobo','瀞天','小蜜','Berg','大大','昶亨','派希','建龍','阿元','阿達','阿育'].map(name=>({name,session:'C'}))
];
const BOSS_ROSTER=[['小宇',10.5,1060,'男','球路控制'],['Kevin',10,1015,'男','重殺壓制'],['阿宏哥',10.5,1080,'男','防守反擊'],['Grace',11,1120,'女','全場調度']];
const DEFAULT_VOICE_ALIASES={阿力:['哈利','阿里','阿莉'],楷翔:['開箱','凱翔','楷祥','凱祥'],懿宏:['義宏','易宏'],菜包:['菜寶'],君:['軍'],阿鴻:['阿宏'],啟原:['起源','啟源'],倫:['輪'],純祥:['春香','純香','存錢','存祥'],Sherry:['雪莉'],Mia:['米亞','米婭'],Sophia:['蘇菲亞'],Neil:['尼爾'],丞毅:['誠意','承毅'],阿何:['阿和']};
function createBossPlayers(){return BOSS_ROSTER.map(([name,signupLevel,rating,gender,specialty],index)=>({id:1001+index,name,signupLevel,rating,gender,level:'教練級',games:0,wait:0,status:'boss',wins:0,losses:0,winStreak:0,wishPoints:10,ratingGainBank:0,attendance:100,partner:'—',preferredPartnerIds:[],blockedPartnerIds:[],availableFrom:'18:00',availableUntil:'22:30',targetGames:99,session:'特別',isBoss:true,specialty}))}
function seededProfile(entry,index){
  let seed=[...entry.name].reduce((sum,char)=>sum+char.charCodeAt(0),index*97+41);seed=(seed*9301+49297)%233280;const signupLevel=5.5+(seed%8)*.5,rating=Math.round(signupLevel*100+((seed>>3)%41)-20),gender=seed%5<2?'女':'男',level=signupLevel>=8?'進階':signupLevel>=6.5?'中階':'初階',combined=entry.session==='B+C';return{id:index+1,name:entry.name,session:entry.session,signupLevel,rating,gender,level,games:0,wait:0,status:'waiting',wins:seed%6,losses:(seed>>4)%6,winStreak:0,wishPoints:3+(seed%5),ratingGainBank:0,attendance:75+(seed%24),partner:'—',preferredPartnerIds:[],blockedPartnerIds:[],availableFrom:entry.session==='C'?'20:30':'18:00',availableUntil:entry.session==='B'?'20:30':'22:30',targetGames:combined?9:5}
}
const state={
  dataVersion:'2026-08-05-first-roster',sessionDate:'2026-08-05',sessionStart:'18:00',sessionEnd:'22:30',pool:'waiting',arrangementMode:'auto',matchTypeMode:'any',manualSelectedPlayerId:null,sidebarCollapsed:false,sound:true,gameLimit:9,finished:0,startedAt:Date.now(),
  players:REGISTRATION_ROSTER.map(seededProfile),
  bossPlayers:createBossPlayers(),
  courts:[1,2,3].map(id=>({id,status:'idle',players:[]})),
  history:[],suggestion:[],simulation:null
};

try{const saved=JSON.parse(localStorage.getItem('badminton-club-state'));if(saved?.dataVersion===state.dataVersion&&saved.players&&saved.courts)Object.assign(state,saved)}catch(e){console.info('使用 8/5 報名名單')}
if(!Array.isArray(state.bossPlayers)||state.bossPlayers.length!==BOSS_ROSTER.length)state.bossPlayers=createBossPlayers();
state.history.forEach((match,index)=>{if(!match.id)match.id=`legacy-${match.court}-${String(match.time).replace(/\W/g,'')}-${index}`;if(match.manualReview==null)match.manualReview='' });
state.players.forEach(p=>{if(p.signupLevel==null)p.signupLevel=Math.max(1,Math.round((p.rating/100)*2)/2)});
state.players.forEach(p=>{
  if(!p.gender)p.gender=p.id%5<2?'女':'男';if(p.wishPoints==null)p.wishPoints=5;if(p.winStreak==null)p.winStreak=0;if(p.ratingGainBank==null)p.ratingGainBank=0;
  p.voiceAliases=[...new Set([...(Array.isArray(p.voiceAliases)?p.voiceAliases:[]),...(DEFAULT_VOICE_ALIASES[p.name]||[])])];
  if(!Array.isArray(p.preferredPartnerIds)){const legacy=state.players.find(x=>x.name===p.partner);p.preferredPartnerIds=legacy?[legacy.id]:[]}
  if(!Array.isArray(p.blockedPartnerIds))p.blockedPartnerIds=[];
  if(!p.availableFrom)p.availableFrom=p.id===10?'19:45':'19:00';
  if(!p.availableUntil)p.availableUntil=p.id===9?'20:30':'22:00';
  if(!p.targetGames)p.targetGames=p.id===9?5:p.id===10?4:state.gameLimit;
});
state.bossPlayers.forEach(p=>{if(!p.gender)p.gender=p.name==='Grace'?'女':'男';if(p.wishPoints==null)p.wishPoints=10;if(p.winStreak==null)p.winStreak=0;if(p.ratingGainBank==null)p.ratingGainBank=0});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], allPlayers=()=>[...state.players,...state.bossPlayers], player=id=>allPlayers().find(p=>p.id===id), safeHtml=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[char]));
function isTouchInterface(){return window.matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0}
let touchPlayerDrag=null,suppressPoolClickUntil=0;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function openModal(html){$('#modal-content').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function renderSidebar(){const collapsed=Boolean(state.sidebarCollapsed),shell=$('#app-shell'),button=$('#sidebar-toggle');shell.classList.toggle('sidebar-collapsed',collapsed);button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'展開選單':'收起選單');button.title=collapsed?'展開選單':'收起選單'}
function toggleSidebar(){state.sidebarCollapsed=!state.sidebarCollapsed;renderSidebar();localStorage.setItem('badminton-club-state',JSON.stringify(state))}
function timeToMinutes(value){const [h,m]=String(value||'00:00').split(':').map(Number);return h*60+m}
function currentSessionMinutes(){const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,minutes=now.getHours()*60+now.getMinutes(),start=timeToMinutes(state.sessionStart),end=timeToMinutes(state.sessionEnd);if(today!==state.sessionDate)return start;return minutes>=start&&minutes<=end?minutes:start}
function activeSession(){return currentSessionMinutes()<timeToMinutes('20:30')?{key:'B',label:'B 時段',courts:2,start:'18:00',end:'20:30'}:{key:'C',label:'C 時段',courts:3,start:'20:30',end:'22:30'}}
function activeCourts(){return state.courts.filter(c=>c.id<=activeSession().courts)}
function sessionRosterCount(key){return state.players.filter(p=>p.session===key||p.session==='B+C').length}
function isAvailableNow(p){const now=currentSessionMinutes();return now>=timeToMinutes(p.availableFrom)&&now<timeToMinutes(p.availableUntil)}
function gamesRemaining(p){return Math.max(0,(p.targetGames||state.gameLimit)-p.games)}
function schedulePriority(p){const now=Math.max(currentSessionMinutes(),timeToMinutes(p.availableFrom)),remainingMinutes=Math.max(0,timeToMinutes(p.availableUntil)-now),possibleSlots=Math.max(1,Math.floor(remainingMinutes/18));return gamesRemaining(p)/possibleSlots}
function availabilityText(p){const now=currentSessionMinutes(),from=timeToMinutes(p.availableFrom),until=timeToMinutes(p.availableUntil);if(now<from)return `${p.availableFrom} 到場`;if(now>=until)return `${p.availableUntil} 已離場`;return `${p.availableUntil} 前 · 尚缺 ${gamesRemaining(p)} 場`}
function todayForm(p){let wins=0,netRating=0,streak=0,stillStreaking=true;for(const match of state.history){const side=match.a?.includes(p.name)?'a':match.b?.includes(p.name)?'b':'';if(!side)continue;const won=match.winner===side;if(won)wins++;netRating+=Number(side==='a'?match.deltaA:match.deltaB)||0;if(stillStreaking&&won)streak++;else if(stillStreaking)stillStreaking=false}return{wins,netRating,streak,hot:wins>=2||netRating>=20||streak>=2}}
function hotPlayerBadge(p){const form=todayForm(p);if(!form.hot)return'';const detail=form.wins>=2?`${form.wins} 勝`:form.netRating>=20?`+${form.netRating}`:`${form.streak} 連勝`;return `<span class="hot-badge" title="今日手感火熱：${detail}">🔥 ${detail}</span>`}
function preferenceNames(ids){return (ids||[]).map(id=>player(id)?.name).filter(Boolean)}
function pairIsBlocked(a,b){return a.blockedPartnerIds.includes(b.id)||b.blockedPartnerIds.includes(a.id)}
function pairIsPreferred(a,b){return a.preferredPartnerIds.includes(b.id)||b.preferredPartnerIds.includes(a.id)}
function suggestionHasBlockedPair(ids){if(ids.length<4)return false;return pairIsBlocked(player(ids[0]),player(ids[1]))||pairIsBlocked(player(ids[2]),player(ids[3]))}
function canJoinSuggestion(p){return p&&(p.status==='waiting'||p.status==='boss')&&isAvailableNow(p)}
function matchTypeFor(players){if(players.length!==4)return '自由雙打';const genders=players.map(p=>p.gender),women=genders.filter(g=>g==='女').length;if(women===0)return '男雙';if(women===4)return '女雙';if(women===2&&players[0].gender!==players[1].gender&&players[2].gender!==players[3].gender)return '混雙';return '自由雙打'}
function suggestionMatchesMode(players,mode=state.matchTypeMode){if(players.length!==4||mode==='any')return true;if(mode==='men')return players.every(p=>p.gender==='男');if(mode==='women')return players.every(p=>p.gender==='女');if(mode==='mixed')return matchTypeFor(players)==='混雙';return true}
function suggestionSignature(players){return players.length===4?[players.slice(0,2).map(p=>p.id).sort((a,b)=>a-b).join('-'),players.slice(2,4).map(p=>p.id).sort((a,b)=>a-b).join('-')].sort().join('|'):''}
function getSuggestion(alternate=false){
  const waiting=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)&&(state.matchTypeMode!=='men'||p.gender==='男')&&(state.matchTypeMode!=='women'||p.gender==='女')).sort((a,b)=>(schedulePriority(b)-schedulePriority(a))||(b.wait-a.wait)||(a.games-b.games));
  const shortlist=waiting.slice(0,Math.min(10,waiting.length)); if(shortlist.length<4){state.suggestion=[];return{candidateCount:0,changed:false}}
  const candidates=new Map();
  for(let a=0;a<shortlist.length-3;a++)for(let b=a+1;b<shortlist.length-2;b++)for(let c=b+1;c<shortlist.length-1;c++)for(let d=c+1;d<shortlist.length;d++){
    const group=[shortlist[a],shortlist[b],shortlist[c],shortlist[d]];
    const options=[[group[0],group[1],group[2],group[3]],[group[0],group[2],group[1],group[3]],[group[0],group[3],group[1],group[2]]];
    for(const o of options){if(!suggestionMatchesMode(o)||pairIsBlocked(o[0],o[1])||pairIsBlocked(o[2],o[3]))continue;const diff=Math.abs(o[0].rating+o[1].rating-o[2].rating-o[3].rating),wait=o.reduce((s,p)=>s+Math.min(p.wait,60),0),urgency=o.reduce((s,p)=>s+schedulePriority(p),0),preference=(pairIsPreferred(o[0],o[1])?1:0)+(pairIsPreferred(o[2],o[3])?1:0),completedTargets=o.filter(p=>gamesRemaining(p)===0).length,score=diff-wait*.6-urgency*55-preference*45+completedTargets*120,signature=suggestionSignature(o),candidate={score,diff,players:o,signature};if(!candidates.has(signature)||score<candidates.get(signature).score)candidates.set(signature,candidate)}
  }
  const ranked=[...candidates.values()].sort((a,b)=>a.score-b.score||a.diff-b.diff);if(!ranked.length){state.suggestion=[];return{candidateCount:0,changed:false}}
  const currentSignature=suggestionSignature(state.suggestion.map(player).filter(Boolean));let chosen=ranked[0];if(alternate&&currentSignature){const currentIndex=ranked.findIndex(item=>item.signature===currentSignature);chosen=ranked[(currentIndex>=0?currentIndex+1:0)%ranked.length]}
  state.suggestion=chosen.players.map(p=>p.id);state.suggestionDiff=chosen.diff;return{candidateCount:ranked.length,changed:chosen.signature!==currentSignature,rank:ranked.indexOf(chosen)+1}
}
function renderCourts(){
  const session=activeSession(),registered=sessionRosterCount(session.key),capacity=session.courts*8;$('#court-session-label').textContent=`${session.label} · ${session.courts} 面 · ${registered}/${capacity} 人`;
  $('#court-grid').dataset.count=session.courts;
  $('#court-grid').innerHTML=activeCourts().map(c=>{
    if(c.status==='idle')return `<article class="court-card idle"><div class="court-top"><strong>球場 ${c.id}</strong><span class="court-status">空場</span></div><div class="court-body"><div class="empty-court"><b>＋</b><span>等待安排</span></div></div><div class="court-actions"><button onclick="assignToCourt(${c.id})">安排候選對戰</button></div></article>`;
    const ps=c.players.map(player);return `<article class="court-card ${c.funMode?'fun-court':''}"><div class="court-top"><strong>球場 ${c.id}${c.funMode?` · ${funModeName(c.funMode)}`:''}</strong><span class="match-type-tag">${matchTypeFor(ps)}</span><span class="court-status">比賽中 · ${Math.floor((Date.now()-c.start)/60000)} 分</span></div><div class="court-body"><div class="court-markings"></div><span class="court-team-label team-a-label">A 隊</span><span class="court-team-label team-b-label">B 隊</span><div class="net"></div><div class="teams"><div class="team team-a">${ps.slice(0,2).map(p=>`<div class="court-player ${p.gender==='女'?'female':''} ${todayForm(p).hot?'hot-player':''}"><strong>${p.isBoss?'👑 ':''}${p.name}<i>${p.gender}</i></strong><span class="court-level"><small>LV</small><b>${p.signupLevel}</b></span><small>${p.rating} 分</small></div>`).join('')}</div><div class="team team-b">${ps.slice(2).map(p=>`<div class="court-player ${p.gender==='女'?'female':''} ${todayForm(p).hot?'hot-player':''}"><strong>${p.isBoss?'👑 ':''}${p.name}<i>${p.gender}</i></strong><span class="court-level"><small>LV</small><b>${p.signupLevel}</b></span><small>${p.rating} 分</small></div>`).join('')}</div></div></div><div class="court-actions"><button onclick="showCourt(${c.id})">查看</button><button onclick="finishCourt(${c.id})">結束比賽</button></div></article>`
  }).join('');
  $('#playing-count').textContent=allPlayers().filter(p=>p.status==='playing').length;$('#onsite-count').textContent=state.players.filter(p=>p.status!=='absent'&&isAvailableNow(p)).length;$('#finished-count').textContent=state.finished;
}
function renderPool(){
  const bossPool=state.pool==='boss',manual=state.arrangementMode==='manual'&&state.pool==='waiting',canDrag=manual&&!isTouchInterface(),nextUpIds=new Set(state.suggestion),regularPool=state.players.filter(p=>p.status===state.pool&&(state.pool!=='waiting'||(isAvailableNow(p)&&!nextUpIds.has(p.id)))),list=bossPool?state.bossPlayers.filter(p=>p.status==='boss'):regularPool;$('#player-pool').classList.toggle('boss-pool',bossPool);$('#player-pool').innerHTML=list.length?list.map(p=>bossPool?`<button class="player-card boss-card ${p.gender==='女'?'female-player':''}" onclick="showBoss(${p.id})"><span class="boss-crown">♛ 魔王</span><span class="gender-badge">${p.gender}</span><strong>${p.name}</strong><div class="rating">⚔ ${p.rating}</div><div class="player-metrics"><span>🏸 ${p.games}</span><span>✦ ${p.wishPoints}</span></div><small class="schedule-meta">${p.specialty}</small></button>`:`<button class="player-card ${p.gender==='女'?'female-player':''} ${todayForm(p).hot?'hot-player':''} ${manual?'manual-selectable':''} ${state.manualSelectedPlayerId===p.id?'selected-player':''}" ${canDrag?`draggable="true"`:''} aria-pressed="${state.manualSelectedPlayerId===p.id}" onclick="handlePoolPlayerClick(${p.id})" ondragstart="startPlayerDrag(event,${p.id})" ondragend="endPlayerDrag(event)">${manual&&isTouchInterface()?`<span class="touch-drag-handle" aria-label="拖曳 ${p.name}" onpointerdown="startTouchPlayerDrag(event,${p.id})">⠿</span>`:''}<span class="level"><small>LV</small><b>${p.signupLevel}</b></span><span class="gender-badge">${p.gender}</span>${hotPlayerBadge(p)}<strong>${p.name}</strong><div class="rating">⚔ ${p.rating}</div><div class="player-metrics"><span class="wait-time">⏱ ${p.wait}</span><span>🏸 ${p.games}/${p.targetGames}</span><span>✦ ${p.wishPoints}</span></div><small class="schedule-meta ${schedulePriority(p)>=.65&&isAvailableNow(p)?'urgent':''}">${p.session} · ${p.availableUntil}</small></button>`).join(''):`<p class="pool-hint">${bossPool?'目前所有魔王都在場上。':state.pool==='waiting'?`${activeSession().label}目前沒有可上場的備戰球友。`:'這個區域目前沒有人。'}</p>`;
  $('#waiting-badge').textContent=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)&&!nextUpIds.has(p.id)).length;['resting','absent'].forEach(k=>$(`#${k}-badge`).textContent=state.players.filter(p=>p.status===k).length);$('#boss-badge').textContent=state.bossPlayers.filter(p=>p.status==='boss').length;$('#pool-availability-hint').textContent=state.pool==='waiting'?`${activeSession().label}只顯示目前可上場且尚未進入候選對戰的球友；🔥 橘框代表今日至少 2 勝、2 連勝或動態積分淨增 20 分。`:'點選球友可查看資料與目前狀態。'
}
function renderSuggestion(){
  if(state.arrangementMode==='auto'&&state.suggestion.length===4&&(state.suggestion.some(id=>!canJoinSuggestion(player(id)))||suggestionHasBlockedPair(state.suggestion)||!suggestionMatchesMode(state.suggestion.map(player))))state.suggestion=[];if(state.suggestion.length<4)getSuggestion();const ps=state.suggestion.map(player);if(ps.length<4){const eligible=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)).length;$('#suggestion-match-type').textContent=state.matchTypeMode==='men'?'男雙':state.matchTypeMode==='women'?'女雙':state.matchTypeMode==='mixed'?'混雙':'自由雙打';$('#suggestion').innerHTML=`<p class="pool-hint">目前 ${eligible} 位備戰球友中找不到符合此雙打模式的 4 人組合，請切換模式或調整性別資料。</p>`;return}
  const manual=state.arrangementMode==='manual',touch=isTouchInterface(),slot=(p,index)=>`<button class="suggestion-player ${p.gender==='女'?'female-player':''} ${todayForm(p).hot?'hot-player':''} ${p.isBoss?'boss-slot':''} ${manual?'drop-target':''}" data-slot="${index}" onclick="handleSuggestionSlotClick(${index})" ondragover="allowSuggestionDrop(event)" ondragleave="leaveSuggestionDrop(event)" ondrop="dropPlayerOnSlot(event,${index})"><strong>${p.isBoss?'👑 ':''}${p.name} <i class="inline-gender">${p.gender}</i></strong><span class="candidate-level"><small>LV</small><b>${p.signupLevel}</b></span><small>${p.rating} 分${p.isBoss?' · 教練級':` · 等 ${p.wait} 分`}</small><small class="candidate-meta">${p.isBoss?`必殺技：${p.specialty}`:`${p.availableUntil} 前 · 目標 ${p.games}/${p.targetGames}${schedulePriority(p)>=.65?' · 優先':''}`}</small>${manual?`<small class="manual-slot-label">${touch?'點此取代':'拖曳或點選以取代'}</small>`:''}</button>`;
  $('#suggestion').innerHTML=`<div class="suggestion-team">${ps.slice(0,2).map((p,i)=>slot(p,i)).join('')}</div><div class="team-total">A 隊動態積分合計 ${ps[0].rating+ps[1].rating}</div><div class="versus">VS</div><div class="suggestion-team">${ps.slice(2).map((p,i)=>slot(p,i+2)).join('')}</div><div class="team-total">B 隊動態積分合計 ${ps[2].rating+ps[3].rating}</div>`;
  const diff=Math.abs(ps[0].rating+ps[1].rating-ps[2].rating-ps[3].rating);state.suggestionDiff=diff;$('#balance-label').textContent=diff<60?'極均衡':diff<120?'均衡':'有挑戰';$('#balance-bar').style.width=`${Math.max(20,100-diff/3)}%`;
  $('#suggestion-match-type').textContent=matchTypeFor(ps);
}
function renderArrangementMode(){
  const manual=state.arrangementMode==='manual',touch=isTouchInterface();$('#next-up-panel').classList.toggle('manual-active',manual);$('#manual-guide').hidden=!manual;$('#voice-command-form').hidden=!manual;$('#manual-guide span').textContent=touch?'點球友再點候選位置，或使用下方語音命令。':'拖曳球友、點選取代，或使用下方語音命令。';$('#auto-mode').classList.toggle('active',!manual);$('#manual-mode').classList.toggle('active',manual);$('#auto-mode').setAttribute('aria-pressed',String(!manual));$('#manual-mode').setAttribute('aria-pressed',String(manual));$('#edit-suggestion').textContent=manual?'完成調整':'調整名單';
}
function setArrangementMode(mode){
  if(mode===state.arrangementMode)return;state.arrangementMode=mode;state.manualSelectedPlayerId=null;state.funMode='';
  if(mode==='manual'){
    state.pool='waiting';$$('#pool-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.pool==='waiting'));toast('手動模式：拖曳球友，或先點球友再點右側位置');
  }else{
    state.suggestion=[];getSuggestion();toast('已切回智慧排點並重新計算組合');
  }
  renderArrangementMode();renderPool();renderSuggestion();localStorage.setItem('badminton-club-state',JSON.stringify(state));
}
function handlePoolPlayerClick(id){
  if(Date.now()<suppressPoolClickUntil)return;
  const p=player(id);if(state.arrangementMode!=='manual'||state.pool!=='waiting')return showPlayer(id);
  if(!p||p.status!=='waiting')return toast('只有備戰區球友可以加入候選對戰');if(!isAvailableNow(p))return toast(`${p.name} 的可上場時段是 ${p.availableFrom}–${p.availableUntil}`);state.manualSelectedPlayerId=state.manualSelectedPlayerId===id?null:id;renderPool();toast(state.manualSelectedPlayerId?`已選取 ${p.name}，請點右側要取代的位置`:'已取消選取');
}
function startPlayerDrag(event,id){
  if(state.arrangementMode!=='manual'||!isAvailableNow(player(id)))return event.preventDefault();state.manualSelectedPlayerId=id;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(id));event.currentTarget.classList.add('dragging');
}
function endPlayerDrag(event){event.currentTarget.classList.remove('dragging');$$('.suggestion-player').forEach(x=>x.classList.remove('drag-over'))}
function allowSuggestionDrop(event){if(state.arrangementMode!=='manual')return;event.preventDefault();event.dataTransfer.dropEffect='move';event.currentTarget.classList.add('drag-over')}
function leaveSuggestionDrop(event){event.currentTarget.classList.remove('drag-over')}
function dropPlayerOnSlot(event,slotIndex){event.preventDefault();event.currentTarget.classList.remove('drag-over');const id=Number(event.dataTransfer.getData('text/plain')||state.manualSelectedPlayerId);replaceSuggestionPlayer(id,slotIndex)}
function startTouchPlayerDrag(event,id){
  if(event.pointerType==='mouse'||state.arrangementMode!=='manual'||!isAvailableNow(player(id)))return;event.preventDefault();event.stopPropagation();cancelTouchPlayerDrag();const card=event.currentTarget.closest('.player-card'),rect=card.getBoundingClientRect(),ghost=card.cloneNode(true);ghost.classList.add('touch-drag-ghost');ghost.style.width=`${rect.width}px`;document.body.appendChild(ghost);touchPlayerDrag={id,handle:event.currentTarget,ghost,target:null};state.manualSelectedPlayerId=id;try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch(error){}event.currentTarget.addEventListener('pointermove',moveTouchPlayerDrag);event.currentTarget.addEventListener('pointerup',finishTouchPlayerDrag);event.currentTarget.addEventListener('pointercancel',cancelTouchPlayerDrag);moveTouchPlayerDrag(event)
}
function moveTouchPlayerDrag(event){if(!touchPlayerDrag)return;event.preventDefault();const{ghost}=touchPlayerDrag;ghost.style.transform=`translate3d(${event.clientX+14}px,${event.clientY+14}px,0)`;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('.suggestion-player[data-slot]');if(touchPlayerDrag.target!==target){touchPlayerDrag.target?.classList.remove('drag-over');target?.classList.add('drag-over');touchPlayerDrag.target=target}}
function finishTouchPlayerDrag(event){if(!touchPlayerDrag)return;event.preventDefault();const{id,target}=touchPlayerDrag,slotIndex=target?Number(target.dataset.slot):-1;cleanupTouchPlayerDrag();suppressPoolClickUntil=Date.now()+500;if(slotIndex>=0)replaceSuggestionPlayer(id,slotIndex);else{renderPool();toast('未放到候選位置；也可以點球友後再點要取代的位置')}}
function cancelTouchPlayerDrag(){if(!touchPlayerDrag)return;cleanupTouchPlayerDrag();renderPool()}
function cleanupTouchPlayerDrag(){if(!touchPlayerDrag)return;const{handle,ghost,target}=touchPlayerDrag;handle.removeEventListener('pointermove',moveTouchPlayerDrag);handle.removeEventListener('pointerup',finishTouchPlayerDrag);handle.removeEventListener('pointercancel',cancelTouchPlayerDrag);target?.classList.remove('drag-over');ghost.remove();touchPlayerDrag=null}
function handleSuggestionSlotClick(slotIndex){
  if(state.arrangementMode!=='manual')return showPlayer(state.suggestion[slotIndex]);if(!state.manualSelectedPlayerId)return toast('請先從左側備戰區選一位球友');replaceSuggestionPlayer(state.manualSelectedPlayerId,slotIndex);
}
function replaceSuggestionPlayer(id,slotIndex){
  const incoming=player(id);if(state.arrangementMode!=='manual'||!incoming||incoming.status!=='waiting')return toast('只能使用備戰區球友');if(!isAvailableNow(incoming))return toast(`${incoming.name} 目前不在可上場時段`);if(slotIndex<0||slotIndex>3)return;
  const oldId=state.suggestion[slotIndex],existingIndex=state.suggestion.indexOf(id);if(existingIndex===slotIndex){state.manualSelectedPlayerId=null;renderPool();return toast(`${incoming.name} 已在這個位置`)}
  const next=[...state.suggestion];if(existingIndex>=0){next[existingIndex]=oldId;next[slotIndex]=id}else next[slotIndex]=id;if(suggestionHasBlockedPair(next)){state.manualSelectedPlayerId=null;renderPool();return toast('此調整會形成拒絕搭檔組合，已取消')};state.suggestion=next;
  const replaced=player(oldId);state.manualSelectedPlayerId=null;renderSuggestion();renderPool();localStorage.setItem('badminton-club-state',JSON.stringify(state));toast(existingIndex>=0?`已交換 ${incoming.name} 與 ${replaced.name}`:`已用 ${incoming.name} 取代 ${replaced.name}`);
}
function normalizeVoiceText(value){return String(value||'').toLowerCase().replace(/[\s，。,.、！!？?：:]/g,'')}
function voiceSlotIndex(text){const value=normalizeVoiceText(text),aliases=[['第一位','第1位','一號','1號','a1','a隊一號','a隊1號','左上'],['第二位','第2位','二號','2號','a2','a隊二號','a隊2號','右上'],['第三位','第3位','三號','3號','b1','b隊一號','b隊1號','左下'],['第四位','第4位','四號','4號','b2','b隊二號','b隊2號','右下']];return aliases.findIndex(group=>group.some(alias=>value.includes(alias)))}
function playerVoiceTerms(p){return[p.name,...(p.voiceAliases||[])]}
function voiceFindPlayer(text,list){const value=normalizeVoiceText(text),terms=[...list].flatMap(p=>playerVoiceTerms(p).map(term=>({p,term:normalizeVoiceText(term)}))).sort((a,b)=>b.term.length-a.term.length);return terms.find(item=>item.term&&value.includes(item.term))?.p}
function voiceCommandParts(command){return String(command||'').split(/換成|換掉|替換成|替換|換/).map(x=>x.trim()).filter(Boolean)}
function resolveVoiceCommand(command){
  const parts=voiceCommandParts(command);if(parts.length<2)return{error:'請使用「阿力換楷翔」或「第一位換阿力」格式'};const current=state.suggestion.map(player).filter(Boolean),left=parts[0],right=parts.slice(1).join(''),slotByPosition=voiceSlotIndex(left),source=voiceFindPlayer(left,current),slotIndex=slotByPosition>=0?slotByPosition:source?current.indexOf(source):-1;if(slotIndex<0)return{error:`候選名單中找不到「${left}」`};const eligible=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)),incoming=voiceFindPlayer(right,eligible);if(!incoming)return{error:`備戰區找不到「${right}」`};return{slotIndex,incoming}
}
function learnCorrectedVoiceCommand(heard,corrected,resolved){const heardParts=voiceCommandParts(heard),correctedParts=voiceCommandParts(corrected);if(heardParts.length<2||correctedParts.length<2)return[];const learned=[],current=state.suggestion.map(player).filter(Boolean),eligible=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)),heardSource=voiceFindPlayer(heardParts[0],current),heardTarget=voiceFindPlayer(heardParts.slice(1).join(''),eligible);if(!heardSource&&voiceSlotIndex(heardParts[0])<0){const source=current[resolved.slotIndex],alias=heardParts[0].trim();if(source&&alias&&!source.voiceAliases.includes(alias)){source.voiceAliases.push(alias);learned.push(`${alias}＝${source.name}`)}}if(!heardTarget){const alias=heardParts.slice(1).join('').trim(),target=resolved.incoming;if(alias&&!target.voiceAliases.includes(alias)){target.voiceAliases.push(alias);learned.push(`${alias}＝${target.name}`)}}return learned}
function applyVoiceCommand(command=$('#voice-command').value){
  if(state.arrangementMode!=='manual')return toast('請先切換為手動模式');const input=$('#voice-command'),spoken=String(command||'').trim();if(!spoken)return toast('請先說出或輸入替換命令');const resolved=resolveVoiceCommand(spoken);if(resolved.error)return toast(resolved.error);const learned=lastUnmatchedTranscript&&normalizeVoiceText(lastUnmatchedTranscript)!==normalizeVoiceText(spoken)?learnCorrectedVoiceCommand(lastUnmatchedTranscript,spoken,resolved):[];lastUnmatchedTranscript='';input.value='';replaceSuggestionPlayer(resolved.incoming.id,resolved.slotIndex);if(learned.length)setTimeout(()=>toast(`已記住：${learned.join('、')}`),120)
}
let voiceRecognition=null;
let lastUnmatchedTranscript='';
function startVoiceCommand(){
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition,input=$('#voice-command'),button=$('#voice-listen');if(!Recognition){input.focus();return toast('此瀏覽器未開放網頁語音辨識，請使用鍵盤麥克風聽寫')}
  if(voiceRecognition){voiceRecognition.stop();return}voiceRecognition=new Recognition();voiceRecognition.lang='zh-TW';voiceRecognition.interimResults=false;voiceRecognition.continuous=false;voiceRecognition.maxAlternatives=5;button.classList.add('listening');button.textContent='● 聆聽中';$('#voice-command-hint').textContent='請說：阿力換楷翔，或第一位換阿力';voiceRecognition.onresult=event=>{const alternatives=Array.from(event.results[0]).map(item=>item.transcript),matched=alternatives.find(text=>!resolveVoiceCommand(text).error),transcript=matched||alternatives[0];input.value=transcript;if(matched){lastUnmatchedTranscript='';applyVoiceCommand(transcript)}else{lastUnmatchedTranscript=transcript;toast(`聽到「${transcript}」，請修正後按套用，系統會自動記住`)} };voiceRecognition.onerror=event=>{if(event.error!=='aborted')toast(event.error==='not-allowed'?'請允許瀏覽器使用麥克風':'沒有聽清楚，請再試一次')};voiceRecognition.onend=()=>{voiceRecognition=null;button.classList.remove('listening');button.textContent='🎙 說話';$('#voice-command-hint').textContent='可說「阿力換楷翔」或「第一位換阿力」'};voiceRecognition.start()
}
function funModeName(mode){return({boss:'魔王挑戰',lucky:'幸運搭檔',revenge:'復仇戰'})[mode]||''}
function shuffle(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function renderFunStatus(){const el=$('#fun-status');if(!el)return;el.textContent=state.funMode?`${funModeName(state.funMode)}已放入候選對戰，可調整或直接安排上場`:'選一個玩法，系統會產生可直接上場的組合'}
function setFunSuggestion(mode,players){state.arrangementMode='auto';state.matchTypeMode='any';$('#match-type-mode').value='any';state.manualSelectedPlayerId=null;state.funMode=mode;state.suggestion=players.map(p=>p.id);renderArrangementMode();renderSuggestion();renderFunStatus();localStorage.setItem('badminton-club-state',JSON.stringify(state));toast(`${funModeName(mode)}組合已產生`);$('#next-up-panel').scrollIntoView({behavior:'smooth',block:'center'})}
function generateFunMatch(mode){
  const waiting=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p));
  if(mode==='boss'){
    const bosses=shuffle(state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p)));if(bosses.length<2||waiting.length<2)return toast('魔王挑戰需要 2 位可上場魔王與 2 位備戰球友');const challengers=[...waiting].sort((a,b)=>b.rating-a.rating).slice(0,2);return setFunSuggestion(mode,[bosses[0],bosses[1],challengers[0],challengers[1]])
  }
  if(mode==='lucky'){
    if(waiting.length<4)return toast('幸運搭檔至少需要 4 位備戰球友');for(let attempt=0;attempt<60;attempt++){const pick=shuffle(waiting).slice(0,4);if(!pairIsBlocked(pick[0],pick[1])&&!pairIsBlocked(pick[2],pick[3]))return setFunSuggestion(mode,pick)}return toast('目前拒絕搭檔條件太多，找不到幸運組合')
  }
  if(mode==='revenge'){
    const last=state.history[0];if(!last)return toast('完成至少一場比賽後，才能啟動復仇戰');const rematch=[...last.a,...last.b].map(name=>allPlayers().find(p=>p.name===name));if(rematch.some(p=>!canJoinSuggestion(p)))return toast('上一場球友尚未全部回到可上場狀態');return setFunSuggestion(mode,rematch)
  }
}
function showBoss(id){const p=player(id);openModal(`<p class="eyebrow">BOSS PROFILE</p><h2>👑 ${p.name}</h2><p class="sub">教練級魔王不占一般報名名額，只會在趣味挑戰中加入排點。</p><div class="boss-profile"><strong>Lv.${p.signupLevel}</strong><span>${p.rating} 動態積分</span><span>必殺技：${p.specialty}</span><span>今晚戰績：${p.wins} 勝 ${p.losses} 敗</span></div><div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="closeModal();generateFunMatch('boss')">發起魔王挑戰</button></div>`)}
const WISH_LABELS={partner:'指定搭檔',opponent:'指定對手',mixed:'想打混雙',boss:'挑戰魔王'};let wishItems=[];
function buildWishSuggestion(wish){const requester=state.players.find(p=>p.name===wish.playerName&&p.status==='waiting'&&isAvailableNow(p));if(!requester)return null;const waiting=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)&&p.id!==requester.id).sort((a,b)=>Math.abs(a.rating-requester.rating)-Math.abs(b.rating-requester.rating));if(wish.type==='partner'){const target=waiting.find(p=>p.name.toLowerCase()===wish.target.toLowerCase()&&!pairIsBlocked(requester,p));if(!target)return null;const others=waiting.filter(p=>p.id!==target.id).slice(0,2);return others.length===2?[requester,target,...others]:null}if(wish.type==='opponent'){const target=waiting.find(p=>p.name.toLowerCase()===wish.target.toLowerCase());if(!target)return null;const others=waiting.filter(p=>p.id!==target.id).slice(0,2);return others.length===2?[requester,others[0],target,others[1]]:null}if(wish.type==='mixed'){const mate=waiting.find(p=>p.gender!==requester.gender&&!pairIsBlocked(requester,p));if(!mate)return null;const left=waiting.filter(p=>p.id!==mate.id),male=left.find(p=>p.gender==='男'),female=left.find(p=>p.gender==='女'&&p.id!==male?.id);if(!male||!female||pairIsBlocked(male,female))return null;return[requester,mate,male,female]}if(wish.type==='boss'){const mate=waiting[0],bosses=shuffle(state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p))).slice(0,2);return mate&&bosses.length===2?[requester,mate,...bosses]:null}return null}
function renderWishPool(){const pending=wishItems.filter(w=>w.status==='pending');$('#admin-wish-list').innerHTML=pending.length?pending.map(w=>{const p=state.players.find(p=>p.name===w.playerName),enough=(p?.wishPoints||0)>=w.cost;return`<article class="wish-card"><div><span>${WISH_LABELS[w.type]}</span><strong>${safeHtml(w.playerName)}</strong><small>${w.target?`對象：${safeHtml(w.target)} · `:''}需要 ${w.cost} 點／目前 ${p?.wishPoints??0} 點</small></div><div><button class="secondary" onclick="rejectWish('${w.id}')">略過</button><button class="primary" ${enough?'':'disabled'} onclick="approveWish('${w.id}')">套用願望</button></div></article>`}).join(''):'<p class="pool-hint">目前還沒有待處理願望。</p>'}
let lastAdminEtag='';
async function adminFetch(url,options={}){const response=await fetch(url,{...options,headers:{...options.headers,...authHeader()}});if(response.status===401)showLoginGate('連線已逾時，請重新登入');return response}
async function refreshWishes(){try{const headers=lastAdminEtag?{'If-None-Match':lastAdminEtag}:undefined;const response=await fetch('/api/live-bundle',{cache:'no-store',headers});if(response.status===304||!response.ok)return;lastAdminEtag=response.headers.get('ETag')||'';wishItems=(await response.json()).wishes||[];renderWishPool()}catch(error){}}
async function approveWish(id){const wish=wishItems.find(w=>w.id===id),p=state.players.find(p=>p.name===wish?.playerName);if(!wish||!p)return;if(p.wishPoints<wish.cost)return toast(`${p.name} 的許願點不足`);const combination=buildWishSuggestion(wish);if(!combination)return toast('目前到場名單無法完成這個願望，請稍後再試');if(suggestionHasBlockedPair(combination.map(p=>p.id)))return toast('願望組合碰到拒絕搭檔設定，請先調整名單');p.wishPoints-=wish.cost;state.arrangementMode='auto';state.matchTypeMode=wish.type==='mixed'?'mixed':'any';$('#match-type-mode').value=state.matchTypeMode;state.funMode=wish.type==='boss'?'boss':'';state.suggestion=combination.map(p=>p.id);await adminFetch('/api/wishes/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'fulfilled'})});render();refreshWishes();toast(`${p.name} 的「${WISH_LABELS[wish.type]}」已套用，扣除 ${wish.cost} 點`);$('#next-up-panel').scrollIntoView({behavior:'smooth',block:'center'})}
async function rejectWish(id){await adminFetch('/api/wishes/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'rejected'})});refreshWishes();toast('願望已略過')}
function renderMembers(){
  const q=$('#member-search')?.value.toLowerCase()||'',lvl=$('#level-filter')?.value||'all';const list=state.players.filter(p=>p.name.toLowerCase().includes(q)&&(lvl==='all'||p.level===lvl));
  $('#member-table').innerHTML=list.map(p=>`<tr><td><button class="member-edit-name" aria-label="編輯 ${p.name}" onclick="showPlayer(${p.id})"><span class="tiny-avatar ${p.gender==='女'?'female-avatar':''}">${p.name[0]}</span><strong>${p.name}</strong><small>點擊編輯</small></button></td><td><span class="gender-table ${p.gender==='女'?'female':''}">${p.gender}</span></td><td><b>Lv.${p.signupLevel}</b></td><td><b>${p.rating}</b></td><td><b class="wish-points">✦ ${p.wishPoints}</b></td><td><span class="pill">${p.level}</span></td><td>${p.attendance}%</td><td>${p.wins+p.losses?Math.round(p.wins/(p.wins+p.losses)*100):0}%</td><td>${preferenceNames(p.preferredPartnerIds).join('、')||'—'}</td><td>${preferenceNames(p.blockedPartnerIds).join('、')||'—'}</td><td><span class="time-window">${p.availableFrom}–${p.availableUntil}</span></td><td><b>${p.games}/${p.targetGames}</b></td></tr>`).join('');
  const avg=Math.round(state.players.reduce((s,p)=>s+p.rating,0)/state.players.length);$('#member-summary').innerHTML=`<div class="summary-card"><span>球團成員</span><strong>${state.players.length}</strong></div><div class="summary-card"><span>平均實力分</span><strong>${avg}</strong></div><div class="summary-card"><span>本月出席率</span><strong>82%</strong></div><div class="summary-card"><span>本月完成場次</span><strong>146</strong></div>`
}
function renderHistory(){
  $('#history-list').innerHTML=state.history.map(h=>`<div class="history-row"><span class="result">球場 ${h.court}${h.activity?`<small>${funModeName(h.activity)}</small>`:''}</span><div class="teams-side"><strong>${h.a.join(' / ')}</strong><small>${h.winner==='a'?'勝方':'對戰組合'}${h.deltaA!=null?` · 積分 ${h.deltaA>=0?'+':''}${h.deltaA}`:''}</small></div><div class="score">${h.score}${h.manualReview?`<small class="admin-review">團主：${safeHtml(h.manualReview)}</small>`:''}</div><div class="teams-side"><strong>${h.b.join(' / ')}</strong><small>${h.winner==='b'?'勝方':'對戰組合'}${h.deltaB!=null?` · 積分 ${h.deltaB>=0?'+':''}${h.deltaB}`:''}</small></div><time>${h.time}</time></div>`).join('');
  const board=[...state.players].sort((a,b)=>(b.wins-b.losses)-(a.wins-a.losses)).slice(0,6);$('#leaderboard').innerHTML=board.map((p,i)=>`<div class="leader-row"><span>${i+1}</span><strong>${p.name}</strong><strong>${p.wins} 勝</strong></div>`).join('')
}
function chooseBalancedFour(candidates){
  const shortlist=[...candidates].sort((a,b)=>(a.simGames-b.simGames)||(b.simWait-a.simWait)||(a.id-b.id)).slice(0,Math.min(8,candidates.length));
  let best=null;
  for(let a=0;a<shortlist.length-3;a++)for(let b=a+1;b<shortlist.length-2;b++)for(let c=b+1;c<shortlist.length-1;c++)for(let d=c+1;d<shortlist.length;d++){
    const g=[shortlist[a],shortlist[b],shortlist[c],shortlist[d]],options=[[g[0],g[1],g[2],g[3]],[g[0],g[2],g[1],g[3]],[g[0],g[3],g[1],g[2]]];
    options.forEach(o=>{const diff=Math.abs(o[0].rating+o[1].rating-o[2].rating-o[3].rating),games=o.reduce((s,p)=>s+p.simGames,0),wait=o.reduce((s,p)=>s+p.simWait,0),score=diff+games*18-wait*1.5;if(!best||score<best.score)best={players:o,diff,score}})
  } return best;
}
function runSimulation(){
  const session=activeSession(),virtual=state.players.filter(p=>p.status!=='absent'&&isAvailableNow(p)).map(p=>({...p,simGames:0,simWait:p.wait||0})),matches=[],duplicateErrors=[];
  for(let round=1;round<=30;round++){
    virtual.forEach(p=>p.simWait+=4);const pick=chooseBalancedFour(virtual);if(!pick)break;const ids=pick.players.map(p=>p.id);if(new Set(ids).size!==4)duplicateErrors.push(round);
    const a=pick.players.slice(0,2),b=pick.players.slice(2);pick.players.forEach(p=>{p.simGames++;p.simWait=0});
    matches.push({round,court:(round-1)%session.courts+1,a:a.map(p=>p.name),b:b.map(p=>p.name),aScore:a.reduce((s,p)=>s+p.rating,0),bScore:b.reduce((s,p)=>s+p.rating,0),diff:pick.diff});
  }
  const counts=virtual.map(p=>p.simGames),diffs=matches.map(m=>m.diff),avgDiff=Math.round(diffs.reduce((s,n)=>s+n,0)/diffs.length),maxDiff=Math.max(...diffs),spread=Math.max(...counts)-Math.min(...counts),std=Math.sqrt(counts.reduce((s,n)=>s+Math.pow(n-counts.reduce((a,b)=>a+b,0)/counts.length,2),0)/counts.length),allPlayed=counts.every(n=>n>0);
  const tests=[
    {name:'即時場地限制',detail:`${session.label} 僅使用已租用場地`,pass:matches.every(m=>m.court<=session.courts),value:`${session.courts} 面`},
    {name:'名單完整性',detail:'每場均為 4 位不重複球友',pass:duplicateErrors.length===0,value:duplicateErrors.length?'異常':'30 / 30'},
    {name:'平均實力平衡',detail:'兩隊總分平均差低於 80 分',pass:avgDiff<80,value:`${avgDiff} 分`},
    {name:'極端差距控制',detail:'單場最大實力差低於 160 分',pass:maxDiff<160,value:`${maxDiff} 分`},
    {name:'參與機會覆蓋',detail:'所有在場球友至少上場一次',pass:allPlayed,value:`${counts.filter(n=>n>0).length} / ${counts.length}`},
    {name:'場次公平分布',detail:'最多與最少上場差距不超過 2 場',pass:spread<=2,value:`差 ${spread} 場`}
  ];
  state.simulation={session:session.key,matches,players:virtual.map(p=>({id:p.id,name:p.name,rating:p.rating,games:p.simGames})),metrics:{avgDiff,maxDiff,spread,std:Number(std.toFixed(2)),total:matches.length,players:virtual.length,courts:session.courts},tests,at:new Date().toISOString()};renderSimulation();localStorage.setItem('badminton-club-state',JSON.stringify(state));toast(`模擬完成：${tests.filter(t=>t.pass).length}/${tests.length} 項通過`)
}
function renderSimulation(){
  const s=state.simulation;if(!s){$('#simulation-metrics').innerHTML='';return}
  const m=s.metrics,pass=s.tests.filter(t=>t.pass).length;$('#simulation-status').textContent=`已完成 ${m.total} 場排點測試`;$('#simulation-time').textContent=new Date(s.at).toLocaleString('zh-TW');
  $('#simulation-metrics').innerHTML=[['時段場地',m.courts||activeSession().courts,'面',`${s.session||activeSession().key} 時段限制`],['測試場次',m.total,'場','完整跑完批次排點'],['參與球友',m.players,'人','排除未報到者'],['平均實力差',m.avgDiff,'分','越低代表越均衡'],['最大實力差',m.maxDiff,'分','檢查極端組合'],['場次標準差',m.std,'','越低代表越公平']].map(([label,value,unit,note],i)=>`<div class="metric-card ${i>2?'good':''}"><span>${label}</span><strong>${value}<small style="display:inline"> ${unit}</small></strong><small>${note}</small></div>`).join('');
  $('#test-score').textContent=`${pass} / ${s.tests.length} 通過`;$('#test-results').innerHTML=s.tests.map(t=>`<div class="test-row"><span class="test-icon ${t.pass?'':'fail'}">${t.pass?'✓':'!'}</span><span><strong>${t.name}</strong><small>${t.detail}</small></span><b>${t.value}</b></div>`).join('');
  const max=Math.max(...s.players.map(p=>p.games));$('#participation-chart').innerHTML=[...s.players].sort((a,b)=>b.games-a.games||b.rating-a.rating).map(p=>`<div class="chart-row"><span>${p.name}</span><div class="chart-bar"><i style="width:${p.games/max*100}%"></i></div><strong>${p.games}</strong></div>`).join('');
  $('#simulation-table').innerHTML=s.matches.map(x=>`<tr><td>#${String(x.round).padStart(2,'0')} · ${x.court||1} 場</td><td><b>${x.a.join(' / ')}</b></td><td>${x.aScore}</td><td><b>${x.b.join(' / ')}</b></td><td>${x.bScore}</td><td>${x.diff}</td><td><span class="quality-pill ${x.diff>=100?'warn':''}">${x.diff<60?'極均衡':x.diff<100?'均衡':'具挑戰'}</span></td></tr>`).join('')
}
function matchReview(match){if(match.manualReview)return match.manualReview;const [a,b]=String(match.score||'0–0').split(/[–-]/).map(Number),margin=Math.abs(a-b);if(match.activity==='boss')return '勇者挑戰魔王，氣氛拉滿！';if(margin<=2)return '激戰到最後一分，精彩拉鋸！';if(margin>=10)return '火力全開，強勢拿下！';return '攻守有來有往，漂亮對決！'}
function publicStats(){const scores=new Map();state.history.forEach(match=>{const [aScore,bScore]=String(match.score).split(/[–-]/).map(Number);[...match.a,...match.b].forEach(name=>{if(!scores.has(name))scores.set(name,{name,wins:0,pointsFor:0,pointsAgainst:0,diff:0})});match.a.forEach(name=>{const item=scores.get(name);item.pointsFor+=aScore;item.pointsAgainst+=bScore;if(match.winner==='a')item.wins++});match.b.forEach(name=>{const item=scores.get(name);item.pointsFor+=bScore;item.pointsAgainst+=aScore;if(match.winner==='b')item.wins++})});return [...scores.values()].map(item=>({...item,diff:item.pointsFor-item.pointsAgainst})).sort((a,b)=>b.wins-a.wins||b.diff-a.diff||b.pointsFor-a.pointsFor)}
function buildPublicSnapshot(){const session=activeSession();return{updatedAt:Date.now(),event:{name:'first🥇羽球臨打團',date:'8/5 週三',venue:'板橋奧創'},session:{key:session.key,label:session.label,courts:session.courts},courts:activeCourts().map(c=>({id:c.id,status:c.status,minutes:c.start?Math.floor((Date.now()-c.start)/60000):0,activity:funModeName(c.funMode),matchType:c.matchType||matchTypeFor(c.players.map(player)),a:c.players.slice(0,2).map(id=>player(id)?.name).filter(Boolean),b:c.players.slice(2,4).map(id=>player(id)?.name).filter(Boolean)})),recent:state.history.slice(0,12).map(match=>({id:match.id,court:match.court,a:match.a,b:match.b,score:match.score,time:match.time,activity:funModeName(match.activity),matchType:match.matchType||'自由雙打',review:matchReview(match),customReview:Boolean(match.manualReview),deltaA:match.deltaA??null,deltaB:match.deltaB??null})),stats:publicStats(),roster:state.players.filter(p=>p.status!=='absent'&&isAvailableNow(p)).map(p=>({name:p.name,gender:p.gender,wishPoints:p.wishPoints})).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW'))}}
let publishTimer,lastPublishedSignature='';
function publishLiveState(){clearTimeout(publishTimer);publishTimer=setTimeout(()=>{const snapshot=buildPublicSnapshot();const {updatedAt,...comparable}=snapshot;const signature=JSON.stringify(comparable);if(signature===lastPublishedSignature)return;lastPublishedSignature=signature;adminFetch('/api/live-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)}).catch(()=>{})},1500)}
async function showLiveBoard(){const url=`${location.origin}/live.html`;openModal(`<p class="eyebrow">PLAYER LIVE BOARD</p><h2>球友即時看板</h2><p class="sub">把下方網址或 QR 分享給球友即可開啟。頁面只公開姓名、比分、趣味數據與留言。</p><div class="share-link"><input id="player-live-url" value="${url}" readonly><button class="secondary" onclick="copyLiveBoardLink()">複製</button></div><div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="window.open('${url}','_blank')">開啟看板</button></div>`)}
async function copyLiveBoardLink(){const input=$('#player-live-url');try{await navigator.clipboard.writeText(input.value);toast('球友看板網址已複製')}catch(error){input.select();document.execCommand('copy');toast('球友看板網址已複製')}}
function render(){renderSidebar();renderCourts();renderArrangementMode();renderSuggestion();renderPool();renderFunStatus();renderWishPool();renderMembers();renderHistory();renderSimulation();localStorage.setItem('badminton-club-state',JSON.stringify(state));publishLiveState()}
function renderElapsed(){const seconds=Math.max(0,Math.floor((Date.now()-state.startedAt)/1000)),h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#elapsed').textContent=`${h}:${m}:${s}`}
function assignToCourt(id){const session=activeSession(),suggested=state.suggestion.map(player);if(id>session.courts)return toast(`${session.label}僅開放 ${session.courts} 面場地`);if(state.suggestion.length<4)return toast('備戰區人數不足');if(new Set(state.suggestion).size!==4)return toast('候選名單有重複球友，請重新調整');if(state.suggestion.some(id=>!canJoinSuggestion(player(id))))return toast('候選名單包含目前不可上場的球友');if(!suggestionMatchesMode(suggested))return toast('目前組合不符合所選的雙打模式');if(suggestionHasBlockedPair(state.suggestion))return toast('候選名單包含拒絕搭檔組合');const c=state.courts.find(c=>c.id===id);if(!c)return toast('找不到可用場地');c.players=[...state.suggestion];c.status='playing';c.start=Date.now();c.funMode=state.funMode||'';c.matchType=matchTypeFor(suggested);state.suggestion.forEach(id=>{const p=player(id);p.status='playing';p.wait=0});const names=state.suggestion.map(id=>player(id).name).join('、');state.suggestion=[];state.funMode='';state.manualSelectedPlayerId=null;getSuggestion();render();toast(`已安排${c.matchType}至球場 ${id}`);if(state.sound&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`請 ${names} 到第 ${id} 場上場`))}}
function finishCourt(id){const c=state.courts.find(c=>c.id===id),ps=c.players.map(player),aRating=ps[0].rating+ps[1].rating,bRating=ps[2].rating+ps[3].rating;openModal(`<p class="eyebrow">RECORD RESULT</p><h2>球場 ${id} · 記錄勝負</h2><p class="sub">完成後球友會回到備戰區，動態積分會依雙方強度使用 Elo 公式更新。</p><div class="result-picker"><div class="result-team"><label>${ps[0].name} / ${ps[1].name}<br>合計 ${aRating}</label><input id="score-a" type="number" value="21" min="0" max="30"></div><b>—</b><div class="result-team"><label>${ps[2].name} / ${ps[3].name}<br>合計 ${bRating}</label><input id="score-b" type="number" value="17" min="0" max="30"></div></div><label class="match-review-input">團主單場評語 <small>選填；留空時由系統依比分產生</small><textarea id="match-review" maxlength="80" placeholder="例如：多拍來回很精彩，兩隊防守都很穩！"></textarea></label><div class="modal-actions"><button class="secondary" data-close>取消</button><button class="primary" onclick="confirmFinish(${id})">完成記錄</button></div>`)}
function awardWishPoints(ps,awin,aTeam,bTeam,deltaA,deltaB){const underdogWon=awin?bTeam-aTeam>=200:aTeam-bTeam>=200;let awarded=0;ps.forEach((p,i)=>{const won=(i<2)===awin,delta=i<2?deltaA:deltaB;if(!won){p.winStreak=0;return}p.winStreak=(p.winStreak||0)+1;let points=1;if(p.winStreak%3===0)points+=2;if(underdogWon)points+=2;p.ratingGainBank=(p.ratingGainBank||0)+Math.max(0,delta);const converted=Math.floor(p.ratingGainBank/25);p.ratingGainBank%=25;points+=converted;p.wishPoints=(p.wishPoints||0)+points;awarded+=points});return{awarded,underdogWon}}
function confirmFinish(id){
  const c=state.courts.find(c=>c.id===id),ps=c.players.map(player),a=+$(`#score-a`).value,b=+$(`#score-b`).value,manualReview=$('#match-review').value.trim().slice(0,80);
  if(a===b)return toast('請輸入有勝負的比分');
  const awin=a>b,aTeam=ps[0].rating+ps[1].rating,bTeam=ps[2].rating+ps[3].rating,expectedA=1/(1+Math.pow(10,(bTeam-aTeam)/800)),k=24,deltaA=Math.round(k*((awin?1:0)-expectedA)),deltaB=-deltaA;
  const wishAward=awardWishPoints(ps,awin,aTeam,bTeam,deltaA,deltaB);
  ps.forEach((p,i)=>{p.status=p.isBoss?'boss':'waiting';p.games++;p.wait=0;const won=(i<2)===awin;if(won)p.wins++;else p.losses++;p.rating=Math.max(100,p.rating+(i<2?deltaA:deltaB))});
  state.history.unshift({id:globalThis.crypto?.randomUUID?.()||`match-${Date.now()}`,court:id,a:[ps[0].name,ps[1].name],b:[ps[2].name,ps[3].name],score:`${a}–${b}`,time:new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}),winner:awin?'a':'b',deltaA,deltaB,activity:c.funMode||'',matchType:c.matchType||matchTypeFor(ps),manualReview,wishPointsAwarded:wishAward.awarded});c.status='idle';c.players=[];c.funMode='';c.matchType='';state.finished++;state.suggestion=[];getSuggestion();closeModal();render();toast(`比分已發布，勝方共獲得 ${wishAward.awarded} 許願點${wishAward.underdogWon?'（含越級成功獎勵）':''}`);if($('#auto-setting').checked)setTimeout(()=>assignToCourt(id),500)
}
function showCourt(id){const c=state.courts.find(c=>c.id===id),ps=c.players.map(player);openModal(`<p class="eyebrow">COURT ${id}</p><h2>場上球友</h2><p class="sub">比賽已進行 ${Math.floor((Date.now()-c.start)/60000)} 分鐘</p>${ps.map((p,i)=>`<div class="leader-row"><span>${i<2?'A':'B'}</span><strong>${p.name}</strong><strong>${p.rating} 分</strong></div>`).join('')}<div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="closeModal();finishCourt(${id})">結束比賽</button></div>`)}
function partnerPicker(p,kind){const chosen=kind==='preferred'?p.preferredPartnerIds:p.blockedPartnerIds;return state.players.filter(x=>x.id!==p.id).map(x=>`<label class="partner-option"><input type="checkbox" data-partner-kind="${kind}" value="${x.id}" ${chosen.includes(x.id)?'checked':''}><span>${x.name}</span></label>`).join('')}
function showPlayer(id){const p=player(id);openModal(`<p class="eyebrow">PLAYER PROFILE</p><h2>${p.name}</h2><p class="sub">性別會用於雙打模式；語音別名可修正同音字辨識。</p><div class="form-grid"><label>性別<select id="edit-gender"><option value="男" ${p.gender==='男'?'selected':''}>男</option><option value="女" ${p.gender==='女'?'selected':''}>女</option></select></label><label>許願點數<input id="edit-wish-points" type="number" min="0" value="${p.wishPoints}"></label><label class="full">語音別名 <small>以逗號分隔，例如：哈利、阿里</small><input id="edit-voice-aliases" value="${safeHtml((p.voiceAliases||[]).join('、'))}" placeholder="常被辨識成的同音字"></label><label>報名等級<input id="edit-signup-level" type="number" min="1" max="15" step="0.5" value="${p.signupLevel}"></label><label>動態積分<input id="edit-rating" type="number" value="${p.rating}"></label><label>程度標籤<select id="edit-level"><option ${p.level==='進階'?'selected':''}>進階</option><option ${p.level==='中階'?'selected':''}>中階</option><option ${p.level==='初階'?'selected':''}>初階</option></select></label><label>已打場數<input id="edit-games" type="number" value="${p.games}"></label><label>可上場時間<input id="edit-available-from" type="time" value="${p.availableFrom}"></label><label>最晚離場時間<input id="edit-available-until" type="time" value="${p.availableUntil}"></label><label>今晚目標場數<input id="edit-target-games" type="number" min="1" max="20" value="${p.targetGames}"></label><label>目前狀態<select id="edit-status"><option value="waiting" ${p.status==='waiting'?'selected':''}>備戰</option><option value="resting" ${p.status==='resting'?'selected':''}>休息</option><option value="absent" ${p.status==='absent'?'selected':''}>未報到</option></select></label><fieldset class="preference-field full"><legend>偏好搭檔 <small>排點時優先同隊，可複選</small></legend><div class="partner-picker">${partnerPicker(p,'preferred')}</div></fieldset><fieldset class="preference-field full danger"><legend>拒絕搭檔 <small>不會被安排在同一隊，可複選</small></legend><div class="partner-picker">${partnerPicker(p,'blocked')}</div></fieldset></div><div class="schedule-explain"><b>語音辨識提示</b><span>系統會用姓名及語音別名比對目前名單，不會把別名顯示給球友。</span></div><div class="modal-actions"><button class="secondary" onclick="resetRatingFromLevel()">依等級重設積分</button><button class="secondary" data-close>取消</button><button class="primary" onclick="savePlayer(${id})">儲存調整</button></div>`)}
function resetRatingFromLevel(){const level=+$('#edit-signup-level').value;if(level>0){$('#edit-rating').value=Math.round(level*100);toast(`已重設為 ${Math.round(level*100)} 分，儲存後生效`)}}
function savePlayer(id){const p=player(id),signupLevel=+$('#edit-signup-level').value,from=$('#edit-available-from').value,until=$('#edit-available-until').value,preferred=$$('[data-partner-kind="preferred"]:checked').map(x=>+x.value),blocked=$$('[data-partner-kind="blocked"]:checked').map(x=>+x.value);if(!signupLevel||signupLevel<1||signupLevel>15)return toast('報名等級請輸入 1–15');if(!from||!until||timeToMinutes(from)>=timeToMinutes(until))return toast('可上場開始時間必須早於離場時間');if(preferred.some(id=>blocked.includes(id)))return toast('同一球友不能同時設為偏好與拒絕搭檔');p.gender=$('#edit-gender').value;p.wishPoints=Math.max(0,+$('#edit-wish-points').value||0);p.voiceAliases=$('#edit-voice-aliases').value.split(/[,，、\n]+/).map(x=>x.trim()).filter(Boolean);p.signupLevel=signupLevel;p.rating=+$('#edit-rating').value;p.level=$('#edit-level').value;p.games=+$('#edit-games').value;p.availableFrom=from;p.availableUntil=until;p.targetGames=Math.max(1,+$('#edit-target-games').value||1);p.preferredPartnerIds=preferred;p.blockedPartnerIds=blocked;p.partner=preferenceNames(preferred)[0]||'—';if(p.status!=='playing')p.status=$('#edit-status').value;state.suggestion=[];state.simulation=null;closeModal();render();toast('球友資料與語音別名已更新')}
function syncInitialRating(){const level=+$('#new-signup-level').value||0;$('#new-rating').value=Math.round(level*100);$('#initial-rating-preview').textContent=`Lv.${level} × 100 = ${Math.round(level*100)} 分 · 初始許願點 3 點`}
function addPerson(){openModal(`<p class="eyebrow">NEW PLAYER</p><h2>新增球友</h2><p class="sub">輸入性別與報名等級後，系統會建立初始資料。</p><div class="form-grid"><label class="full">暱稱<input id="new-name" placeholder="例如：小羽"></label><label>性別<select id="new-gender"><option value="男">男</option><option value="女">女</option></select></label><label>報名等級<input id="new-signup-level" type="number" min="1" max="15" step="0.5" value="7" oninput="syncInitialRating()"></label><label>初始動態積分<input id="new-rating" type="number" value="700" readonly></label><label>程度標籤<select id="new-level"><option>中階</option><option>進階</option><option>初階</option></select></label><label>今晚目標場數<input id="new-target-games" type="number" min="1" max="20" value="7"></label><label>可上場時間<input id="new-available-from" type="time" value="19:00"></label><label>最晚離場時間<input id="new-available-until" type="time" value="22:00"></label><p id="initial-rating-preview" class="sub full">Lv.7 × 100 = 700 分 · 初始許願點 3 點</p></div><div class="modal-actions"><button class="secondary" data-close>取消</button><button class="primary" onclick="confirmAdd()">加入名單</button></div>`)}
function confirmAdd(){const name=$('#new-name').value.trim(),signupLevel=+$('#new-signup-level').value,from=$('#new-available-from').value,until=$('#new-available-until').value;if(!name)return toast('請輸入暱稱');if(!signupLevel||signupLevel<1||signupLevel>15)return toast('報名等級請輸入 1–15');if(timeToMinutes(from)>=timeToMinutes(until))return toast('可上場開始時間必須早於離場時間');const rating=Math.round(signupLevel*100);state.players.push({id:Date.now(),name,gender:$('#new-gender').value,signupLevel,rating,level:$('#new-level').value,games:0,wait:0,status:'waiting',wins:0,losses:0,winStreak:0,wishPoints:3,ratingGainBank:0,attendance:100,partner:'—',voiceAliases:[],preferredPartnerIds:[],blockedPartnerIds:[],availableFrom:from,availableUntil:until,targetGames:Math.max(1,+$('#new-target-games').value||1)});state.suggestion=[];state.simulation=null;closeModal();render();toast(`${name} 已以 Lv.${signupLevel}／${rating} 分加入備戰區`)}

$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));$('#modal').addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeModal()});
function activateView(view){const b=$(`.nav-item[data-view="${view}"]`);if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}-view`).classList.add('active');const titles={courts:'今晚，一起打場好球',members:'讓每位球友都有位置',history:'每場對戰都值得記住',simulation:'用數據驗證每一次排點',settings:'排出公平，也排出樂趣'};$('#page-title').textContent=titles[view];history.replaceState(null,'',`?view=${view}`)}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b)activateView(b.dataset.view)});
$('#sidebar-toggle').onclick=toggleSidebar;
$('#open-live-board').onclick=showLiveBoard;
$('#pool-tabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$$('#pool-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.pool=b.dataset.pool;renderPool()});
$('#auto-mode').onclick=()=>setArrangementMode('auto');$('#manual-mode').onclick=()=>setArrangementMode('manual');
$('#voice-listen').onclick=startVoiceCommand;$('#voice-command-form').onsubmit=event=>{event.preventDefault();applyVoiceCommand()};
$('#match-type-mode').value=state.matchTypeMode;$('#match-type-mode').onchange=event=>{state.matchTypeMode=event.target.value;state.suggestion=[];state.funMode='';getSuggestion();renderSuggestion();renderPool();renderFunStatus();localStorage.setItem('badminton-club-state',JSON.stringify(state));toast(`已切換為 ${event.target.selectedOptions[0].textContent}`)};
$$('[data-fun]').forEach(button=>button.onclick=()=>generateFunMatch(button.dataset.fun));
$('#refresh-match').onclick=()=>{state.funMode='';const result=getSuggestion(true);renderSuggestion();renderPool();renderFunStatus();localStorage.setItem('badminton-club-state',JSON.stringify(state));if(!result.candidateCount)toast('目前沒有符合條件的四人組合');else if(!result.changed)toast('目前限制下只有這一種合格組合');else toast(`已切換至第 ${result.rank}/${result.candidateCount} 個均衡方案`)};
$('#assign-match').onclick=()=>{const c=activeCourts().find(c=>c.status==='idle');c?assignToCourt(c.id):toast(`${activeSession().label}目前沒有空場`)};$('#auto-arrange').onclick=$('#assign-match').onclick;
$('#add-player').onclick=addPerson;$('#add-member').onclick=addPerson;$('#member-search').oninput=renderMembers;$('#level-filter').onchange=renderMembers;
$('#sound-toggle').onclick=()=>{state.sound=!state.sound;$('#sound-toggle').textContent=state.sound?'♬':'♩';toast(state.sound?'語音播報已開啟':'語音播報已靜音')};
$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
$$('[data-step]').forEach(b=>b.onclick=()=>{state.gameLimit=Math.max(1,state.gameLimit+ +b.dataset.delta);$('#limit-setting').textContent=state.gameLimit});
$('#save-settings').onclick=()=>toast('排點設定已儲存');$('#edit-suggestion').onclick=()=>setArrangementMode(state.arrangementMode==='manual'?'auto':'manual');
$('#export-history').onclick=()=>{const rows=['場地,A隊,B隊,比分,時間',...state.history.map(h=>`${h.court},${h.a.join('/')},${h.b.join('/')},${h.score},${h.time}`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}));a.download='羽球對戰紀錄.csv';a.click();URL.revokeObjectURL(a.href)};
$('#run-simulation').onclick=runSimulation;$('#export-simulation').onclick=()=>{if(!state.simulation)return toast('請先執行模擬測試');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.simulation,null,2)],{type:'application/json'}));a.download='排點模擬測試報告.json';a.click();URL.revokeObjectURL(a.href)};
function bootConsole(){setInterval(renderElapsed,1000);setInterval(()=>{state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)).forEach(p=>p.wait++);renderCourts();renderSuggestion();renderPool();localStorage.setItem('badminton-club-state',JSON.stringify(state));publishLiveState()},60000);setInterval(refreshWishes,5000);renderElapsed();render();refreshWishes();if(!state.simulation||state.simulation.session!==activeSession().key)runSimulation();activateView(new URLSearchParams(location.search).get('view')||'courts')}
let consoleBooted=false;
// sessionStorage rather than a cookie: the Static Web Apps proxy strips Set-Cookie from managed functions.
const TOKEN_KEY='badminton-admin-token';
const adminToken=()=>sessionStorage.getItem(TOKEN_KEY)||'';
function authHeader(){const token=adminToken();return token?{Authorization:`Bearer ${token}`}:{}}
function showLoginGate(message){sessionStorage.removeItem(TOKEN_KEY);$('#login-gate').hidden=false;if(message){const error=$('#login-error');error.textContent=message;error.hidden=false}$('#login-username').focus()}
function hideLoginGate(){$('#login-gate').hidden=true;$('#login-error').hidden=true}
function enterConsole(){hideLoginGate();if(consoleBooted)return;consoleBooted=true;bootConsole()}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#login-submit');button.disabled=true;try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#login-username').value,password:$('#login-password').value})});const result=await response.json().catch(()=>({}));if(response.ok&&result.token){$('#login-password').value='';sessionStorage.setItem(TOKEN_KEY,result.token);enterConsole()}else{const error=$('#login-error');error.textContent=result.error||'登入失敗';error.hidden=false}}catch(error){const box=$('#login-error');box.textContent='無法連線，請稍後再試';box.hidden=false}finally{button.disabled=false}});
$('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',headers:authHeader()}).catch(()=>{});sessionStorage.removeItem(TOKEN_KEY);location.reload()};
(async()=>{if(adminToken())try{const response=await fetch('/api/auth/me',{cache:'no-store',headers:authHeader()});if(response.ok&&(await response.json()).authenticated)return enterConsole()}catch(error){}showLoginGate()})();
