const REGISTRATION_ROSTER=[
  ...[['阿力','B'],['楷翔','B+C'],['懿宏','B+C'],['Duke','B'],['菜包','B'],['君','B'],['阿鴻','B'],['啟原','B+C'],['倫','B'],['純祥','B'],['Sherry','B'],['Mia','B'],['Sophia','B'],['Neil','B'],['丞毅','B'],['阿何','B']].map(([name,session])=>({name,session})),
  ...['欣寧','Elva','商商','政輝','Casper','Ariel','家瑋','羅強','Bobo','瀞天','小蜜','Berg','大大','昶亨','派希','建龍','阿元','阿達','阿育'].map(name=>({name,session:'C'}))
];
const BOSS_ROSTER=[['小宇',10.5,1060,'男','球路控制'],['Kevin',10,1015,'男','重殺壓制'],['阿宏哥',10.5,1080,'男','防守反擊'],['Grace',11,1120,'女','全場調度']];
const DEFAULT_VOICE_ALIASES={阿力:['哈利','阿里','阿莉'],楷翔:['開箱','凱翔','楷祥','凱祥'],懿宏:['義宏','易宏'],菜包:['菜寶'],君:['軍'],阿鴻:['阿宏'],啟原:['起源','啟源'],倫:['輪'],純祥:['春香','純香','存錢','存祥'],Sherry:['雪莉'],Mia:['米亞','米婭'],Sophia:['蘇菲亞'],Neil:['尼爾'],丞毅:['誠意','承毅'],阿何:['阿和']};
function createBossPlayers(){return BOSS_ROSTER.map(([name,signupLevel,rating,gender,specialty],index)=>({id:1001+index,name,signupLevel,rating,gender,level:'教練級',games:0,wait:0,status:'boss',wins:0,losses:0,winStreak:0,wishPoints:10,ratingGainBank:0,attendance:100,partner:'—',preferredPartnerIds:[],blockedPartnerIds:[],availableFrom:'18:00',availableUntil:'22:30',targetGames:99,session:'特別',isBoss:true,specialty}))}
function seededProfile(entry,index){
  let seed=[...entry.name].reduce((sum,char)=>sum+char.charCodeAt(0),index*97+41);seed=(seed*9301+49297)%233280;const signupLevel=5.5+(seed%8)*.5,rating=Math.round(signupLevel*100+((seed>>3)%41)-20),gender=seed%5<2?'女':'男',level=signupLevel>=8?'進階':signupLevel>=6.5?'中階':'初階',combined=entry.session==='B+C';return{id:index+1,name:entry.name,session:entry.session,signupLevel,rating,gender,level,games:0,wait:0,status:'waiting',paid:false,wins:seed%6,losses:(seed>>4)%6,winStreak:0,wishPoints:3+(seed%5),ratingGainBank:0,attendance:75+(seed%24),partner:'—',preferredPartnerIds:[],blockedPartnerIds:[],boundPartnerId:null,boundSession:'B+C',availableFrom:entry.session==='C'?'20:30':'18:00',availableUntil:entry.session==='B'?'20:30':'22:30',targetGames:combined?9:5}
}
const state={
  dataVersion:'2026-08-05-first-roster',savedAt:0,sessionDate:'2026-08-05',sessionDateLabel:'8/5 週三',eventName:'first🥇羽球臨打團',venue:'板橋奧創',shuttle:'勝利藍蓋 B-01N＋K3',sessionStart:'18:00',sessionEnd:'22:30',pool:'waiting',arrangementMode:'auto',matchTypeMode:'any',manualSelectedPlayerId:null,paymentReminderOpen:false,sidebarCollapsed:false,sound:true,gameLimit:9,finished:0,startedAt:Date.now(),sessionOverrideKey:'auto',simulationSessionKey:'B',
  players:REGISTRATION_ROSTER.map(seededProfile),
  rosterIds:REGISTRATION_ROSTER.map((_,index)=>index+1),
  bossPlayers:createBossPlayers(),
  courts:[1,2,3].map(id=>({id,status:'idle',players:[]})),
  history:[],suggestion:[],simulation:null
};

const STATE_KEY='badminton-club-state';
try{const saved=JSON.parse(localStorage.getItem(STATE_KEY));if(saved?.dataVersion===state.dataVersion&&saved.players&&saved.courts)Object.assign(state,saved)}catch(e){console.info('使用 8/5 報名名單')}
// Two admin tabs each hold their own copy of state, so an unguarded write silently discards
// whatever the other tab did. Stamp every save and let the older tab adopt the newer state.
let applyingRemoteState=false;
function saveState(){if(applyingRemoteState)return;state.savedAt=Date.now();localStorage.setItem(STATE_KEY,JSON.stringify(state))}
window.addEventListener('storage',event=>{
  if(event.key!==STATE_KEY||!event.newValue)return;
  let incoming;try{incoming=JSON.parse(event.newValue)}catch(error){return}
  if(incoming?.dataVersion!==state.dataVersion||!incoming.players||!(incoming.savedAt>(state.savedAt||0)))return;
  applyingRemoteState=true;
  try{Object.assign(state,incoming);render()}finally{applyingRemoteState=false}
});
if(!Array.isArray(state.bossPlayers)||state.bossPlayers.length!==BOSS_ROSTER.length)state.bossPlayers=createBossPlayers();
if(!Array.isArray(state.rosterIds))state.rosterIds=state.players.map(p=>p.id);
if(!['auto','B','C'].includes(state.sessionOverrideKey))state.sessionOverrideKey='auto';
if(!['B','C'].includes(state.simulationSessionKey))state.simulationSessionKey='B';
state.rosterIds=state.rosterIds.filter(id=>state.players.some(p=>p.id===id));
state.history.forEach((match,index)=>{if(!match.id)match.id=`legacy-${match.court}-${String(match.time).replace(/\W/g,'')}-${index}`;if(match.manualReview==null)match.manualReview='' });
state.players.forEach(p=>{if(p.signupLevel==null)p.signupLevel=Math.max(1,Math.round((p.rating/100)*2)/2)});
state.players.forEach(p=>{
  if(!p.gender)p.gender=p.id%5<2?'女':'男';if(typeof p.paid!=='boolean')p.paid=false;if(p.wishPoints==null)p.wishPoints=5;if(p.winStreak==null)p.winStreak=0;if(p.ratingGainBank==null)p.ratingGainBank=0;
  p.voiceAliases=[...new Set([...(Array.isArray(p.voiceAliases)?p.voiceAliases:[]),...(DEFAULT_VOICE_ALIASES[p.name]||[])])];
  if(!Array.isArray(p.preferredPartnerIds)){const legacy=state.players.find(x=>x.name===p.partner);p.preferredPartnerIds=legacy?[legacy.id]:[]}
  if(!Array.isArray(p.blockedPartnerIds))p.blockedPartnerIds=[];
  if(!state.players.some(x=>x.id===p.boundPartnerId))p.boundPartnerId=null;
  if(!['B','C','B+C'].includes(p.boundSession))p.boundSession='B+C';
  if(!p.availableFrom)p.availableFrom=p.id===10?'19:45':'19:00';
  if(!p.availableUntil)p.availableUntil=p.id===9?'20:30':'22:00';
  if(!p.targetGames)p.targetGames=p.id===9?5:p.id===10?4:state.gameLimit;
});
state.bossPlayers.forEach(p=>{if(!p.gender)p.gender=p.name==='Grace'?'女':'男';if(p.wishPoints==null)p.wishPoints=10;if(p.winStreak==null)p.winStreak=0;if(p.ratingGainBank==null)p.ratingGainBank=0});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], rosterPlayers=()=>state.players.filter(p=>state.rosterIds.includes(p.id)),isRosterPlayer=p=>Boolean(p&&state.rosterIds.includes(p.id)),allPlayers=()=>[...state.players,...state.bossPlayers], player=id=>allPlayers().find(p=>p.id===id), safeHtml=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[char]));
function fitVisibleNames(root=document){requestAnimationFrame(()=>root.querySelectorAll('.fit-name').forEach(label=>{label.style.fontSize='';let size=parseFloat(getComputedStyle(label).fontSize)||15;const minimum=label.closest('.suggestion-player')?9:10;while(label.scrollWidth>label.clientWidth+1&&size>minimum){size-=.5;label.style.fontSize=`${size}px`}}))}
function isTouchInterface(){return window.matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0}
let touchPlayerDrag=null,suppressPoolClickUntil=0;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function openModal(html){$('#modal-content').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function updateConnectivityStatus(){const online=navigator.onLine,button=$('#connectivity-status');if(!button)return;button.classList.toggle('offline',!online);button.classList.toggle('online',online);button.querySelector('span').textContent=online?'線上同步':'離線排點';button.title=online?'網路正常；場次會同步到球友看板與 LINE':'離線模式；排點資料仍會保存在本機，雲端功能暫停'}
function showOfflineGuide(){const online=navigator.onLine;openModal(`<p class="eyebrow">OFFLINE MODE</p><h2>${online?'可安裝離線版':'目前使用離線排點'}</h2><p class="sub">排點、比分、成員與積分會持續保存在這台裝置；恢復網路後會自動把最新公開狀態同步到 Azure。</p><div class="offline-guide"><strong>${online?'iPad 安裝方式':'離線期間仍可使用'}</strong><span>${online?'使用 Safari 開啟正式網站，點「分享」→「加入主畫面」。第一次安裝與更新版本時需要網路。':'今日排點、建立場次、成員管理、記錄比分、動態積分與模擬測試。'}</span><strong>離線時暫停</strong><span>球友即時看板、LINE 查詢、留言、許願池與跨裝置同步。</span></div><div class="modal-actions"><button class="primary" data-close>知道了</button></div>`)}
function registerOfflineApp(){updateConnectivityStatus();window.addEventListener('offline',()=>{updateConnectivityStatus();toast('已切換離線排點；資料會保存在本機')});window.addEventListener('online',()=>{updateConnectivityStatus();lastPublishedSignature='';publishLiveState();refreshWishes();toast('網路已恢復，正在同步最新場次')});if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{})}
function renderSidebar(){const collapsed=Boolean(state.sidebarCollapsed),shell=$('#app-shell'),button=$('#sidebar-toggle');shell.classList.toggle('sidebar-collapsed',collapsed);button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'展開選單':'收起選單');button.title=collapsed?'展開選單':'收起選單';$('#sidebar-session-date').textContent=`${state.sessionDateLabel}場次`;$('#sidebar-event-name').textContent=state.eventName;$('#sidebar-session-venue').textContent=`${state.sessionStart}–${state.sessionEnd} · ${state.venue}`}
function toggleSidebar(){state.sidebarCollapsed=!state.sidebarCollapsed;renderSidebar();saveState()}
function timeToMinutes(value){const [h,m]=String(value||'00:00').split(':').map(Number);return h*60+m}
function currentSessionMinutes(){if(state.sessionOverrideKey==='B')return timeToMinutes('18:00');if(state.sessionOverrideKey==='C')return timeToMinutes('20:30');const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,minutes=now.getHours()*60+now.getMinutes(),start=timeToMinutes(state.sessionStart),end=timeToMinutes(state.sessionEnd);if(today!==state.sessionDate)return start;return minutes>=start&&minutes<=end?minutes:start}
function sessionByKey(key){return key==='C'?{key:'C',label:'C 時段',courts:3,start:'20:30',end:'22:30'}:{key:'B',label:'B 時段',courts:2,start:'18:00',end:'20:30'}}
function activeSession(){return sessionByKey(currentSessionMinutes()<timeToMinutes('20:30')?'B':'C')}
function simulationSession(){return sessionByKey(state.simulationSessionKey)}
function activeCourts(){return state.courts.filter(c=>c.id<=activeSession().courts)}
function sessionRosterCount(key){return rosterPlayers().filter(p=>p.session===key||p.session==='B+C').length}
function isAvailableNow(p){const now=currentSessionMinutes();return now>=timeToMinutes(p.availableFrom)&&now<timeToMinutes(p.availableUntil)}
function isAvailableForSession(p,session){return (p.session===session.key||p.session==='B+C')&&timeToMinutes(p.availableFrom)<timeToMinutes(session.end)&&timeToMinutes(p.availableUntil)>timeToMinutes(session.start)}
function gamesRemaining(p){return Math.max(0,(p.targetGames||state.gameLimit)-p.games)}
function schedulePriority(p){const now=Math.max(currentSessionMinutes(),timeToMinutes(p.availableFrom)),remainingMinutes=Math.max(0,timeToMinutes(p.availableUntil)-now),possibleSlots=Math.max(1,Math.floor(remainingMinutes/18));return gamesRemaining(p)/possibleSlots}
function availabilityText(p){const now=currentSessionMinutes(),from=timeToMinutes(p.availableFrom),until=timeToMinutes(p.availableUntil);if(now<from)return `${p.availableFrom} 到場`;if(now>=until)return `${p.availableUntil} 已離場`;return `${p.availableUntil} 前 · 尚缺 ${gamesRemaining(p)} 場`}
function todayForm(p){let wins=0,netRating=0,streak=0,stillStreaking=true;for(const match of state.history){const side=match.a?.includes(p.name)?'a':match.b?.includes(p.name)?'b':'';if(!side)continue;const won=match.winner===side;if(won)wins++;netRating+=Number(side==='a'?match.deltaA:match.deltaB)||0;if(stillStreaking&&won)streak++;else if(stillStreaking)stillStreaking=false}return{wins,netRating,streak,hot:wins>=2||netRating>=20||streak>=2}}
function hotPlayerBadge(p){const form=todayForm(p);if(!form.hot)return'';const detail=form.wins>=2?`${form.wins} 勝`:form.netRating>=20?`+${form.netRating}`:`${form.streak} 連勝`;return `<span class="hot-badge" title="今日手感火熱：${detail}">🔥 ${detail}</span>`}
function poolBindingBadge(p){const mate=boundPartner(p);return mate?`<span class="pool-binding-badge" title="拖入候選時會連同 ${safeHtml(mate.name)} 一起上場">🔗 ${safeHtml(mate.name)}</span>`:''}
function paymentGameTag(p){const label=p.paid?'已付費':'未付費';return `<span class="level payment-level game-target-level ${p.paid?'paid':'unpaid'}" role="button" tabindex="0" aria-label="${safeHtml(p.name)} 已打 ${p.games} 場、目標 ${p.targetGames} 場，${label}，點擊切換" title="已打 ${p.games}/${p.targetGames} 場｜${label}｜點擊切換" draggable="false" ondragstart="event.preventDefault();event.stopPropagation()" onclick="event.preventDefault();event.stopPropagation();togglePlayerPaid(${p.id})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();togglePlayerPaid(${p.id})}"><b>${p.games}/${p.targetGames}</b><i aria-hidden="true">${p.paid?'✓':'×'}</i></span>`}
function preferenceNames(ids){return (ids||[]).map(id=>player(id)?.name).filter(Boolean)}
function pairIsBlocked(a,b){return a.blockedPartnerIds.includes(b.id)||b.blockedPartnerIds.includes(a.id)}
function pairIsPreferred(a,b){return a.preferredPartnerIds.includes(b.id)||b.preferredPartnerIds.includes(a.id)}
function suggestionHasBlockedPair(ids){if(ids.length<4)return false;return pairIsBlocked(player(ids[0]),player(ids[1]))||pairIsBlocked(player(ids[2]),player(ids[3]))}
function bindingIsActive(p,key=activeSession().key){return Boolean(p?.boundPartnerId&&(p.boundSession==='B+C'||p.boundSession===key))}
function boundPartner(p,key=activeSession().key){return bindingIsActive(p,key)?state.players.find(x=>x.id===p.boundPartnerId):null}
function suggestionRespectsBindings(players,key=activeSession().key){if(players.length!==4)return false;return players.every((p,index)=>{const mate=boundPartner(p,key);if(!mate)return true;const mateIndex=players.findIndex(x=>x.id===mate.id);return mateIndex>=0&&Math.floor(index/2)===Math.floor(mateIndex/2)})}
function canJoinSuggestion(p){return p&&(p.status==='boss'||isRosterPlayer(p))&&(p.status==='waiting'||p.status==='boss')&&isAvailableNow(p)}
function canManuallySelectPlayer(p){return Boolean(p&&canJoinSuggestion(p)&&(p.status==='waiting'||p.status==='boss'))}
function matchTypeFor(players){if(players.length!==4)return '自由雙打';const genders=players.map(p=>p.gender),women=genders.filter(g=>g==='女').length;if(women===0)return '男雙';if(women===4)return '女雙';if(women===2&&players[0].gender!==players[1].gender&&players[2].gender!==players[3].gender)return '混雙';return '自由雙打'}
function suggestionMatchesMode(players,mode=state.matchTypeMode){if(players.length!==4||mode==='any')return true;if(mode==='men')return players.every(p=>p.gender==='男');if(mode==='women')return players.every(p=>p.gender==='女');if(mode==='mixed')return matchTypeFor(players)==='混雙';return true}
function suggestionSignature(players){return players.length===4?[players.slice(0,2).map(p=>p.id).sort((a,b)=>a-b).join('-'),players.slice(2,4).map(p=>p.id).sort((a,b)=>a-b).join('-')].sort().join('|'):''}
function getSuggestion(alternate=false){
  const eligible=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)&&(state.matchTypeMode!=='men'||p.gender==='男')&&(state.matchTypeMode!=='women'||p.gender==='女')),eligibleIds=new Set(eligible.map(p=>p.id));
  const waiting=eligible.filter(p=>{const mate=boundPartner(p);return !mate||eligibleIds.has(mate.id)}).sort((a,b)=>(schedulePriority(b)-schedulePriority(a))||(b.wait-a.wait)||(a.games-b.games));
  const shortlist=waiting.slice(0,Math.min(10,waiting.length));shortlist.slice().forEach(p=>{const mate=boundPartner(p);if(mate&&!shortlist.some(x=>x.id===mate.id))shortlist.push(mate)});if(shortlist.length<4){state.suggestion=[];return{candidateCount:0,changed:false}}
  const candidates=new Map();
  for(let a=0;a<shortlist.length-3;a++)for(let b=a+1;b<shortlist.length-2;b++)for(let c=b+1;c<shortlist.length-1;c++)for(let d=c+1;d<shortlist.length;d++){
    const group=[shortlist[a],shortlist[b],shortlist[c],shortlist[d]];
    const options=[[group[0],group[1],group[2],group[3]],[group[0],group[2],group[1],group[3]],[group[0],group[3],group[1],group[2]]];
    for(const o of options){if(!suggestionMatchesMode(o)||!suggestionRespectsBindings(o)||pairIsBlocked(o[0],o[1])||pairIsBlocked(o[2],o[3]))continue;const diff=Math.abs(o[0].rating+o[1].rating-o[2].rating-o[3].rating),wait=o.reduce((s,p)=>s+Math.min(p.wait,60),0),urgency=o.reduce((s,p)=>s+schedulePriority(p),0),preference=(pairIsPreferred(o[0],o[1])?1:0)+(pairIsPreferred(o[2],o[3])?1:0),completedTargets=o.filter(p=>gamesRemaining(p)===0).length,score=diff-wait*.6-urgency*55-preference*45+completedTargets*120,signature=suggestionSignature(o),candidate={score,diff,players:o,signature};if(!candidates.has(signature)||score<candidates.get(signature).score)candidates.set(signature,candidate)}
  }
  const ranked=[...candidates.values()].sort((a,b)=>a.score-b.score||a.diff-b.diff);if(!ranked.length){state.suggestion=[];return{candidateCount:0,changed:false}}
  const currentSignature=suggestionSignature(state.suggestion.map(player).filter(Boolean));let chosen=ranked[0];if(alternate&&currentSignature){const currentIndex=ranked.findIndex(item=>item.signature===currentSignature);chosen=ranked[(currentIndex>=0?currentIndex+1:0)%ranked.length]}
  state.suggestion=chosen.players.map(p=>p.id);state.suggestionDiff=chosen.diff;return{candidateCount:ranked.length,changed:chosen.signature!==currentSignature,rank:ranked.indexOf(chosen)+1}
}
function renderCourts(){
  const session=activeSession(),registered=sessionRosterCount(session.key),capacity=session.courts*8;$('#court-session-label').textContent=`${session.label} · ${session.courts} 面 · ${registered}/${capacity} 人`;
  $('#court-session-switch').value=state.sessionOverrideKey;
  $('#session-date-badge').textContent=state.sessionDateLabel||state.sessionDate;
  $('#announcement').textContent=`B 時段 18:00–20:30 · C 時段 20:30–22:30 · ${state.venue} · 使用${state.shuttle}`;
  $('#court-grid').dataset.count=session.courts;
  $('#court-grid').innerHTML=activeCourts().map(c=>{
    if(c.status==='idle')return `<article class="court-card idle"><div class="court-top"><strong>球場 ${c.id}</strong><span class="court-status">空場</span></div><div class="court-body"><div class="empty-court"><b>＋</b><span>等待安排</span></div></div><div class="court-actions"><button onclick="assignToCourt(${c.id})">安排候選對戰</button></div></article>`;
    const ps=c.players.map(player),courtPlayer=p=>`<div class="court-player ${p.gender==='女'?'female':''} ${todayForm(p).hot?'hot-player':''}"><strong class="fit-name">${p.isBoss?'👑 ':''}${p.name}<i>${p.gender}</i></strong><span class="court-games"><b>${p.games}/${p.targetGames}</b></span><small>${p.rating} 分 · Lv.${p.signupLevel}</small></div>`;return `<article class="court-card ${c.funMode?'fun-court':''}"><div class="court-top"><strong>球場 ${c.id}${c.funMode?` · ${funModeName(c.funMode)}`:''}</strong><span class="match-type-tag">${matchTypeFor(ps)}</span><span class="court-status">比賽中 · ${Math.floor((Date.now()-c.start)/60000)} 分</span></div><div class="court-body"><div class="court-markings"></div><span class="court-team-label team-a-label">A 隊</span><span class="court-team-label team-b-label">B 隊</span><div class="net"></div><div class="teams"><div class="team team-a">${ps.slice(0,2).map(courtPlayer).join('')}</div><div class="team team-b">${ps.slice(2).map(courtPlayer).join('')}</div></div></div><div class="court-actions"><button onclick="showCourt(${c.id})">查看</button><button onclick="finishCourt(${c.id})">結束比賽</button></div></article>`
  }).join('');
  $('#playing-count').textContent=allPlayers().filter(p=>p.status==='playing').length;$('#onsite-count').textContent=rosterPlayers().filter(p=>p.status!=='absent'&&isAvailableNow(p)).length;$('#finished-count').textContent=state.finished;
  fitVisibleNames($('#court-grid'));
}
function switchCourtSession(key){if(!['auto','B','C'].includes(key))return;const select=$('#court-session-switch');if(state.courts.some(c=>c.status==='playing')){select.value=state.sessionOverrideKey;return toast('請先結束進行中的比賽，再切換時段')}state.sessionOverrideKey=key;state.suggestion=[];state.manualSelectedPlayerId=null;state.pool='waiting';getSuggestion();render();toast(key==='auto'?`已恢復依時間自動切換，目前為 ${activeSession().label}`:`已切換至 ${key} 時段試排`)}
function renderPool(){
  const bossPool=state.pool==='boss',manual=state.arrangementMode==='manual'&&(state.pool==='waiting'||bossPool),canDrag=manual&&!isTouchInterface(),nextUpIds=new Set(state.suggestion);
  const regularPool=rosterPlayers().filter(p=>p.status===state.pool&&(state.pool!=='waiting'||(isAvailableNow(p)&&!nextUpIds.has(p.id))));
  const list=bossPool?state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p)&&!nextUpIds.has(p.id)):regularPool;
  $('#player-pool').classList.toggle('boss-pool',bossPool);
  $('#player-pool').innerHTML=list.length?list.map(p=>bossPool
    ?`<button class="player-card boss-card ${p.gender==='女'?'female-player':''} ${manual?'manual-selectable':''} ${state.manualSelectedPlayerId===p.id?'selected-player':''}" ${canDrag?`draggable="true"`:''} aria-pressed="${state.manualSelectedPlayerId===p.id}" onclick="handlePoolPlayerClick(${p.id})" ondragstart="startPlayerDrag(event,${p.id})" ondragend="endPlayerDrag(event)">${manual&&isTouchInterface()?`<span class="touch-drag-handle" aria-label="拖曳 ${safeHtml(p.name)}" onpointerdown="startTouchPlayerDrag(event,${p.id})">⠿</span>`:''}<span class="boss-crown">♛ 魔王</span><span class="level game-target-level boss-game-level"><b>${p.games}/${p.targetGames}</b></span><span class="gender-badge">${p.gender}</span><strong class="fit-name" title="${safeHtml(p.name)}">${safeHtml(p.name)}</strong><div class="rating">⚔ ${p.rating}</div><div class="player-metrics"><span class="secondary-level">Lv.${p.signupLevel}</span><span>✦ ${p.wishPoints}</span></div><small class="schedule-meta">${manual?'點選或拖曳至候選區':p.specialty}</small></button>`
    :`<button class="player-card ${p.gender==='女'?'female-player':''} ${todayForm(p).hot?'hot-player':''} ${manual?'manual-selectable':''} ${state.manualSelectedPlayerId===p.id?'selected-player':''}" ${canDrag?`draggable="true"`:''} aria-pressed="${state.manualSelectedPlayerId===p.id}" onclick="handlePoolPlayerClick(${p.id})" ondragstart="startPlayerDrag(event,${p.id})" ondragend="endPlayerDrag(event)">${manual&&isTouchInterface()?`<span class="touch-drag-handle" aria-label="拖曳 ${p.name}" onpointerdown="startTouchPlayerDrag(event,${p.id})">⠿</span>`:''}<span class="session-remove" role="button" tabindex="0" aria-label="將 ${p.name} 移出本場" title="臨時不來：移出本場" onclick="event.stopPropagation();removePlayerFromSession(${p.id})">×</span>${paymentGameTag(p)}<span class="gender-badge">${p.gender}</span>${hotPlayerBadge(p)}${poolBindingBadge(p)}<strong class="fit-name" title="${safeHtml(p.name)}">${safeHtml(p.name)}</strong><div class="rating">⚔ ${p.rating}</div><div class="player-metrics"><span class="wait-time">⏱ ${p.wait}</span><span class="secondary-level">Lv.${p.signupLevel}</span><span>✦ ${p.wishPoints}</span></div><small class="schedule-meta session-tag session-${p.session==='B+C'?'bc':p.session.toLowerCase()} ${schedulePriority(p)>=.65&&isAvailableNow(p)?'urgent':''}">${p.session}</small></button>`).join('')
    :`<p class="pool-hint">${bossPool?'目前所有魔王都在場上。':state.pool==='waiting'?`${activeSession().label}目前沒有可上場的備戰球友。`:'這個區域目前沒有人。'}</p>`;
  $('#waiting-badge').textContent=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)&&!nextUpIds.has(p.id)).length;
  ['resting','absent'].forEach(k=>$(`#${k}-badge`).textContent=rosterPlayers().filter(p=>p.status===k).length);
  $('#boss-badge').textContent=state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p)&&!nextUpIds.has(p.id)).length;
  $('#pool-availability-hint').textContent=state.pool==='waiting'?`${activeSession().label}只顯示目前可上場且尚未進入候選對戰的球友；× 可將臨時不來的球友移出本場。`:bossPool&&manual?'魔王可像備戰球友一樣點選或拖曳至候選位置。':'點選球友可查看資料與目前狀態。'
  fitVisibleNames($('#player-pool'));
  renderPaymentReminder();
}
function paymentSessionOrder(p){return p.session==='B'?0:p.session==='B+C'?1:2}
function renderPaymentReminder(){
  const roster=rosterPlayers(),unpaid=roster.filter(p=>!p.paid).sort((a,b)=>paymentSessionOrder(a)-paymentSessionOrder(b)||a.name.localeCompare(b.name,'zh-TW')),paidCount=roster.length-unpaid.length,open=Boolean(state.paymentReminderOpen&&unpaid.length),box=$('#payment-reminder');if(!box)return;
  box.classList.toggle('all-paid',!unpaid.length);box.classList.toggle('open',open);$('#unpaid-count').textContent=unpaid.length;$('#payment-summary').textContent=unpaid.length?`已付 ${paidCount}/${roster.length} 人 · 點此查看名單`:`本場 ${roster.length} 人皆已付費`;$('#payment-reminder-toggle').setAttribute('aria-expanded',String(open));$('#unpaid-player-list').hidden=!open;$('#unpaid-player-list').innerHTML=open?unpaid.map(p=>`<button type="button" onclick="togglePlayerPaid(${p.id},true)" title="點擊標記為已付費"><strong>${safeHtml(p.name)}</strong><small>${p.session}</small><span>$ 未付</span></button>`).join(''):'';
}
function togglePaymentReminder(){state.paymentReminderOpen=!state.paymentReminderOpen;renderPaymentReminder();saveState()}
function togglePlayerPaid(id,paid){const p=state.players.find(member=>member.id===id);if(!p||!isRosterPlayer(p))return toast('此球友不在目前場次');p.paid=typeof paid==='boolean'?paid:!p.paid;renderPool();saveState();toast(`${p.name} 已標記為${p.paid?'已付費':'未付費'}`)}
function renderSuggestion(){
  if(state.arrangementMode==='auto'&&state.suggestion.length===4&&(state.suggestion.some(id=>!canJoinSuggestion(player(id)))||suggestionHasBlockedPair(state.suggestion)||!suggestionMatchesMode(state.suggestion.map(player))||!suggestionRespectsBindings(state.suggestion.map(player))))state.suggestion=[];if(state.suggestion.length<4)getSuggestion();const ps=state.suggestion.map(player);if(ps.length<4){const eligible=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)).length;$('#suggestion-match-type').textContent=state.matchTypeMode==='men'?'男雙':state.matchTypeMode==='women'?'女雙':state.matchTypeMode==='mixed'?'混雙':'自由雙打';$('#suggestion').innerHTML=`<p class="pool-hint">目前 ${eligible} 位備戰球友中找不到符合雙打模式與綁定規則的 4 人組合，請檢查時段、狀態或綁定設定。</p>`;return}
  const manual=state.arrangementMode==='manual',touch=isTouchInterface(),slot=(p,index)=>`<button class="suggestion-player ${p.gender==='女'?'female-player':''} ${todayForm(p).hot?'hot-player':''} ${p.isBoss?'boss-slot':''} ${manual?'drop-target':''}" data-slot="${index}" onclick="handleSuggestionSlotClick(${index})" ondragover="allowSuggestionDrop(event)" ondragleave="leaveSuggestionDrop(event)" ondrop="dropPlayerOnSlot(event,${index})"><strong class="fit-name" title="${safeHtml(p.name)}">${p.isBoss?'👑 ':''}${safeHtml(p.name)}</strong><span class="candidate-level candidate-games"><b>${p.games}/${p.targetGames}</b></span><span class="gender-badge candidate-gender-badge">${p.gender}</span><small class="candidate-score">⚔ ${p.rating} 分 · Lv.${p.signupLevel}</small><small class="candidate-meta">${p.isBoss?`教練級 · ${p.specialty}`:`${p.availableUntil} 前${schedulePriority(p)>=.65?' · 優先':''}`}</small>${manual?`<small class="manual-slot-label">${touch?'點此取代':'拖曳或點選以取代'}</small>`:''}</button>`;
  $('#suggestion').innerHTML=`<div class="suggestion-team">${ps.slice(0,2).map((p,i)=>slot(p,i)).join('')}</div><div class="team-total">A 隊動態積分合計 ${ps[0].rating+ps[1].rating}</div><div class="versus">VS</div><div class="suggestion-team">${ps.slice(2).map((p,i)=>slot(p,i+2)).join('')}</div><div class="team-total">B 隊動態積分合計 ${ps[2].rating+ps[3].rating}</div>`;
  const diff=Math.abs(ps[0].rating+ps[1].rating-ps[2].rating-ps[3].rating);state.suggestionDiff=diff;$('#balance-label').textContent=diff<60?'極均衡':diff<120?'均衡':'有挑戰';$('#balance-bar').style.width=`${Math.max(20,100-diff/3)}%`;
  $('#suggestion-match-type').textContent=matchTypeFor(ps);
  fitVisibleNames($('#suggestion'));
}
function renderArrangementMode(){
  const manual=state.arrangementMode==='manual',touch=isTouchInterface();$('#next-up-panel').classList.toggle('manual-active',manual);$('#manual-guide').hidden=!manual;$('#voice-command-form').hidden=!manual;$('#manual-guide span').textContent=touch?'點球友再點候選位置；綁定球友會成對帶入。':'拖曳球友到候選位置；綁定球友會成對取代同隊兩格。';$('#auto-mode').classList.toggle('active',!manual);$('#manual-mode').classList.toggle('active',manual);$('#auto-mode').setAttribute('aria-pressed',String(!manual));$('#manual-mode').setAttribute('aria-pressed',String(manual));$('#edit-suggestion').textContent=manual?'完成調整':'調整名單';
}
function setArrangementMode(mode){
  if(mode===state.arrangementMode)return;state.arrangementMode=mode;state.manualSelectedPlayerId=null;state.funMode='';
  if(mode==='manual'){
    state.pool='waiting';$$('#pool-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.pool==='waiting'));toast('手動模式：拖曳球友，或先點球友再點右側位置');
  }else{
    state.suggestion=[];getSuggestion();toast('已切回智慧排點並重新計算組合');
  }
  renderArrangementMode();renderPool();renderSuggestion();saveState();
}
function handlePoolPlayerClick(id){
  if(Date.now()<suppressPoolClickUntil)return;
  const p=player(id),selectablePool=state.pool==='waiting'||state.pool==='boss';if(state.arrangementMode!=='manual'||!selectablePool)return p?.isBoss?showBoss(id):showPlayer(id);
  if(!canManuallySelectPlayer(p))return toast('只有目前可上場的備戰球友或魔王可以加入候選對戰');state.manualSelectedPlayerId=state.manualSelectedPlayerId===id?null:id;renderPool();const mate=p.isBoss?null:boundPartner(p);toast(state.manualSelectedPlayerId?`已選取 ${p.name}${mate?`（會連同 ${mate.name}）`:''}，請點右側要取代的位置`:'已取消選取');
}
function startPlayerDrag(event,id){
  if(state.arrangementMode!=='manual'||!canManuallySelectPlayer(player(id)))return event.preventDefault();state.manualSelectedPlayerId=id;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(id));event.currentTarget.classList.add('dragging');
}
function endPlayerDrag(event){event.currentTarget.classList.remove('dragging');$$('.suggestion-player').forEach(x=>x.classList.remove('drag-over'))}
function allowSuggestionDrop(event){if(state.arrangementMode!=='manual')return;event.preventDefault();event.dataTransfer.dropEffect='move';event.currentTarget.classList.add('drag-over')}
function leaveSuggestionDrop(event){event.currentTarget.classList.remove('drag-over')}
function dropPlayerOnSlot(event,slotIndex){event.preventDefault();event.currentTarget.classList.remove('drag-over');const id=Number(event.dataTransfer.getData('text/plain')||state.manualSelectedPlayerId);replaceSuggestionPlayer(id,slotIndex)}
function startTouchPlayerDrag(event,id){
  if(event.pointerType==='mouse'||state.arrangementMode!=='manual'||!canManuallySelectPlayer(player(id)))return;event.preventDefault();event.stopPropagation();cancelTouchPlayerDrag();const card=event.currentTarget.closest('.player-card'),rect=card.getBoundingClientRect(),ghost=card.cloneNode(true);ghost.classList.add('touch-drag-ghost');ghost.style.width=`${rect.width}px`;document.body.appendChild(ghost);touchPlayerDrag={id,handle:event.currentTarget,ghost,target:null};state.manualSelectedPlayerId=id;try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch(error){}event.currentTarget.addEventListener('pointermove',moveTouchPlayerDrag);event.currentTarget.addEventListener('pointerup',finishTouchPlayerDrag);event.currentTarget.addEventListener('pointercancel',cancelTouchPlayerDrag);moveTouchPlayerDrag(event)
}
function moveTouchPlayerDrag(event){if(!touchPlayerDrag)return;event.preventDefault();const{ghost}=touchPlayerDrag;ghost.style.transform=`translate3d(${event.clientX+14}px,${event.clientY+14}px,0)`;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('.suggestion-player[data-slot]');if(touchPlayerDrag.target!==target){touchPlayerDrag.target?.classList.remove('drag-over');target?.classList.add('drag-over');touchPlayerDrag.target=target}}
function finishTouchPlayerDrag(event){if(!touchPlayerDrag)return;event.preventDefault();const{id,target}=touchPlayerDrag,slotIndex=target?Number(target.dataset.slot):-1;cleanupTouchPlayerDrag();suppressPoolClickUntil=Date.now()+500;if(slotIndex>=0)replaceSuggestionPlayer(id,slotIndex);else{renderPool();toast('未放到候選位置；也可以點球友後再點要取代的位置')}}
function cancelTouchPlayerDrag(){if(!touchPlayerDrag)return;cleanupTouchPlayerDrag();renderPool()}
function cleanupTouchPlayerDrag(){if(!touchPlayerDrag)return;const{handle,ghost,target}=touchPlayerDrag;handle.removeEventListener('pointermove',moveTouchPlayerDrag);handle.removeEventListener('pointerup',finishTouchPlayerDrag);handle.removeEventListener('pointercancel',cancelTouchPlayerDrag);target?.classList.remove('drag-over');ghost.remove();touchPlayerDrag=null}
function handleSuggestionSlotClick(slotIndex){
  if(state.arrangementMode!=='manual')return showPlayer(state.suggestion[slotIndex]);if(!state.manualSelectedPlayerId)return toast('請先從左側備戰區或魔王區選一位球友');replaceSuggestionPlayer(state.manualSelectedPlayerId,slotIndex);
}
function replaceSuggestionPlayer(id,slotIndex){
  const incoming=player(id);if(state.arrangementMode!=='manual'||!canManuallySelectPlayer(incoming))return toast('只能使用目前可上場的備戰球友或魔王');if(slotIndex<0||slotIndex>3)return;
  const oldId=state.suggestion[slotIndex],existingIndex=state.suggestion.indexOf(id),mate=boundPartner(incoming);
  if(mate){
    if(!canJoinSuggestion(mate))return toast(`綁定球友 ${mate.name} 目前不在備戰區或不可上場`);const mateIndex=state.suggestion.indexOf(mate.id);if(existingIndex>=0||mateIndex>=0){state.manualSelectedPlayerId=null;renderPool();return toast(`${incoming.name} 與 ${mate.name} 已在候選名單中`)}
    const pairedSlot=slotIndex%2===0?slotIndex+1:slotIndex-1,next=[...state.suggestion],replaced=[player(next[slotIndex]),player(next[pairedSlot])];next[slotIndex]=incoming.id;next[pairedSlot]=mate.id;if(suggestionHasBlockedPair(next)){state.manualSelectedPlayerId=null;renderPool();return toast('成對替換後會形成拒絕搭檔組合，已取消')}if(!suggestionRespectsBindings(next.map(player))){state.manualSelectedPlayerId=null;renderPool();return toast('成對替換會影響候選名單中的其他綁定球友，已取消')}state.suggestion=next;state.manualSelectedPlayerId=null;renderSuggestion();renderPool();saveState();return toast(`已帶入 ${incoming.name}、${mate.name}，取代 ${replaced.map(p=>p?.name).filter(Boolean).join('、')}`)
  }
  if(existingIndex===slotIndex){state.manualSelectedPlayerId=null;renderPool();return toast(`${incoming.name} 已在這個位置`)}
  const next=[...state.suggestion];if(existingIndex>=0){next[existingIndex]=oldId;next[slotIndex]=id}else next[slotIndex]=id;if(suggestionHasBlockedPair(next)){state.manualSelectedPlayerId=null;renderPool();return toast('此調整會形成拒絕搭檔組合，已取消')}if(!suggestionRespectsBindings(next.map(player))){state.manualSelectedPlayerId=null;renderPool();return toast('此位置屬於綁定組合，請改拖曳另一組綁定球友取代整隊')};state.suggestion=next;
  const replaced=player(oldId);state.manualSelectedPlayerId=null;renderSuggestion();renderPool();saveState();toast(existingIndex>=0?`已交換 ${incoming.name} 與 ${replaced.name}`:`已用 ${incoming.name} 取代 ${replaced.name}`);
}
function normalizeVoiceText(value){return String(value||'').toLowerCase().replace(/[\s，。,.、！!？?：:]/g,'')}
function voiceSlotIndex(text){const value=normalizeVoiceText(text),aliases=[['第一位','第1位','一號','1號','a1','a隊一號','a隊1號','左上'],['第二位','第2位','二號','2號','a2','a隊二號','a隊2號','右上'],['第三位','第3位','三號','3號','b1','b隊一號','b隊1號','左下'],['第四位','第4位','四號','4號','b2','b隊二號','b隊2號','右下']];return aliases.findIndex(group=>group.some(alias=>value.includes(alias)))}
function playerVoiceTerms(p){return[p.name,...(p.voiceAliases||[])]}
function voiceFindPlayer(text,list){const value=normalizeVoiceText(text),terms=[...list].flatMap(p=>playerVoiceTerms(p).map(term=>({p,term:normalizeVoiceText(term)}))).sort((a,b)=>b.term.length-a.term.length);return terms.find(item=>item.term&&value.includes(item.term))?.p}
function voiceCommandParts(command){return String(command||'').split(/換成|換掉|替換成|替換|換/).map(x=>x.trim()).filter(Boolean)}
function resolveVoiceCommand(command){
  const parts=voiceCommandParts(command);if(parts.length<2)return{error:'請使用「阿力換楷翔」或「第一位換阿力」格式'};const current=state.suggestion.map(player).filter(Boolean),left=parts[0],right=parts.slice(1).join(''),slotByPosition=voiceSlotIndex(left),source=voiceFindPlayer(left,current),slotIndex=slotByPosition>=0?slotByPosition:source?current.indexOf(source):-1;if(slotIndex<0)return{error:`候選名單中找不到「${left}」`};const eligible=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)),incoming=voiceFindPlayer(right,eligible);if(!incoming)return{error:`備戰區找不到「${right}」`};return{slotIndex,incoming}
}
function learnCorrectedVoiceCommand(heard,corrected,resolved){const heardParts=voiceCommandParts(heard),correctedParts=voiceCommandParts(corrected);if(heardParts.length<2||correctedParts.length<2)return[];const learned=[],current=state.suggestion.map(player).filter(Boolean),eligible=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)),heardSource=voiceFindPlayer(heardParts[0],current),heardTarget=voiceFindPlayer(heardParts.slice(1).join(''),eligible);if(!heardSource&&voiceSlotIndex(heardParts[0])<0){const source=current[resolved.slotIndex],alias=heardParts[0].trim();if(source&&alias&&!source.voiceAliases.includes(alias)){source.voiceAliases.push(alias);learned.push(`${alias}＝${source.name}`)}}if(!heardTarget){const alias=heardParts.slice(1).join('').trim(),target=resolved.incoming;if(alias&&!target.voiceAliases.includes(alias)){target.voiceAliases.push(alias);learned.push(`${alias}＝${target.name}`)}}return learned}
function applyVoiceCommand(command=$('#voice-command').value){
  if(state.arrangementMode!=='manual')return toast('請先切換為手動模式');const input=$('#voice-command'),spoken=String(command||'').trim();if(!spoken)return toast('請先說出或輸入替換命令');const resolved=resolveVoiceCommand(spoken);if(resolved.error)return toast(resolved.error);const learned=lastUnmatchedTranscript&&normalizeVoiceText(lastUnmatchedTranscript)!==normalizeVoiceText(spoken)?learnCorrectedVoiceCommand(lastUnmatchedTranscript,spoken,resolved):[];lastUnmatchedTranscript='';input.value='';replaceSuggestionPlayer(resolved.incoming.id,resolved.slotIndex);if(learned.length)setTimeout(()=>toast(`已記住：${learned.join('、')}`),120)
}
let voiceRecognition=null;
let lastUnmatchedTranscript='';
function startVoiceCommand(){
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition,input=$('#voice-command'),button=$('#voice-listen');if(!Recognition){input.focus();return toast('此瀏覽器未開放網頁語音辨識，請使用鍵盤麥克風聽寫')}
  if(voiceRecognition){voiceRecognition.stop();return}voiceRecognition=new Recognition();voiceRecognition.lang='zh-TW';voiceRecognition.interimResults=false;voiceRecognition.continuous=false;voiceRecognition.maxAlternatives=5;button.classList.add('listening');button.textContent='● 聆聽中';$('#voice-command-hint').textContent='請說：阿力換楷翔，或第一位換阿力';voiceRecognition.onresult=event=>{const alternatives=Array.from(event.results[0]).map(item=>item.transcript),matched=alternatives.find(text=>!resolveVoiceCommand(text).error),transcript=matched||alternatives[0];input.value=transcript;if(matched){lastUnmatchedTranscript='';applyVoiceCommand(transcript)}else{lastUnmatchedTranscript=transcript;toast(`聽到「${transcript}」，請修正後按套用，系統會自動記住`)} };voiceRecognition.onerror=event=>{if(event.error!=='aborted')toast(event.error==='not-allowed'?'請允許瀏覽器使用麥克風':'沒有聽清楚，請再試一次')};voiceRecognition.onend=()=>{voiceRecognition=null;button.classList.remove('listening');button.textContent='🎙 說話';$('#voice-command-hint').textContent='可說「阿力換楷翔」或「第一位換阿力」'};voiceRecognition.start()
}
function funModeName(mode){return({boss:'魔王挑戰',lucky:'幸運搭檔',revenge:'復仇戰'})[mode]||''}
function shuffle(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function renderFunStatus(){const el=$('#fun-status');if(!el)return;el.textContent=state.funMode?`${funModeName(state.funMode)}已放入候選對戰，可調整或直接安排上場`:'選一個玩法，系統會產生可直接上場的組合'}
function setFunSuggestion(mode,players){if(!suggestionRespectsBindings(players))return toast('此趣味組合會拆開綁定球友，請稍後再試');state.arrangementMode='auto';state.matchTypeMode='any';$('#match-type-mode').value='any';state.manualSelectedPlayerId=null;state.funMode=mode;state.suggestion=players.map(p=>p.id);renderArrangementMode();renderSuggestion();renderFunStatus();saveState();toast(`${funModeName(mode)}組合已產生`);$('#next-up-panel').scrollIntoView({behavior:'smooth',block:'center'})}
function generateFunMatch(mode){
  const waiting=rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p));
  if(mode==='boss'){
    const bosses=shuffle(state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p)));if(bosses.length<2||waiting.length<2)return toast('魔王挑戰需要 2 位可上場魔王與 2 位備戰球友');const challengers=[...waiting].sort((a,b)=>b.rating-a.rating).slice(0,2);return setFunSuggestion(mode,[bosses[0],bosses[1],challengers[0],challengers[1]])
  }
  if(mode==='lucky'){
    if(waiting.length<4)return toast('幸運搭檔至少需要 4 位備戰球友');for(let attempt=0;attempt<60;attempt++){const pick=shuffle(waiting).slice(0,4);if(suggestionRespectsBindings(pick)&&!pairIsBlocked(pick[0],pick[1])&&!pairIsBlocked(pick[2],pick[3]))return setFunSuggestion(mode,pick)}return toast('目前綁定或拒絕搭檔條件太多，找不到幸運組合')
  }
  if(mode==='revenge'){
    const last=state.history[0];if(!last)return toast('完成至少一場比賽後，才能啟動復仇戰');const rematch=[...last.a,...last.b].map(name=>allPlayers().find(p=>p.name===name));if(rematch.some(p=>!canJoinSuggestion(p)))return toast('上一場球友尚未全部回到可上場狀態');return setFunSuggestion(mode,rematch)
  }
}
function showBoss(id){const p=player(id);openModal(`<p class="eyebrow">BOSS PROFILE</p><h2>👑 ${p.name}</h2><p class="sub">教練級魔王不占一般報名名額，只會在趣味挑戰中加入排點。</p><div class="boss-profile"><strong>Lv.${p.signupLevel}</strong><span>${p.rating} 動態積分</span><span>必殺技：${p.specialty}</span><span>今晚戰績：${p.wins} 勝 ${p.losses} 敗</span></div><div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="closeModal();generateFunMatch('boss')">發起魔王挑戰</button></div>`)}
const WISH_LABELS={partner:'指定搭檔',opponent:'指定對手',mixed:'想打混雙',boss:'挑戰魔王'};let wishItems=[];
function buildWishSuggestion(wish){const requester=state.players.find(p=>p.name===wish.playerName&&p.status==='waiting'&&isAvailableNow(p));if(!requester)return null;const waiting=state.players.filter(p=>p.status==='waiting'&&isAvailableNow(p)&&p.id!==requester.id).sort((a,b)=>Math.abs(a.rating-requester.rating)-Math.abs(b.rating-requester.rating));if(wish.type==='partner'){const target=waiting.find(p=>p.name.toLowerCase()===wish.target.toLowerCase()&&!pairIsBlocked(requester,p));if(!target)return null;const others=waiting.filter(p=>p.id!==target.id).slice(0,2);return others.length===2?[requester,target,...others]:null}if(wish.type==='opponent'){const target=waiting.find(p=>p.name.toLowerCase()===wish.target.toLowerCase());if(!target)return null;const others=waiting.filter(p=>p.id!==target.id).slice(0,2);return others.length===2?[requester,others[0],target,others[1]]:null}if(wish.type==='mixed'){const mate=waiting.find(p=>p.gender!==requester.gender&&!pairIsBlocked(requester,p));if(!mate)return null;const left=waiting.filter(p=>p.id!==mate.id),male=left.find(p=>p.gender==='男'),female=left.find(p=>p.gender==='女'&&p.id!==male?.id);if(!male||!female||pairIsBlocked(male,female))return null;return[requester,mate,male,female]}if(wish.type==='boss'){const mate=waiting[0],bosses=shuffle(state.bossPlayers.filter(p=>p.status==='boss'&&isAvailableNow(p))).slice(0,2);return mate&&bosses.length===2?[requester,mate,...bosses]:null}return null}
function renderWishPool(){const pending=wishItems.filter(w=>w.status==='pending');$('#admin-wish-list').innerHTML=pending.length?pending.map(w=>{const p=state.players.find(p=>p.name===w.playerName),enough=(p?.wishPoints||0)>=w.cost;return`<article class="wish-card"><div><span>${WISH_LABELS[w.type]}</span><strong>${safeHtml(w.playerName)}</strong><small>${w.target?`對象：${safeHtml(w.target)} · `:''}需要 ${w.cost} 點／目前 ${p?.wishPoints??0} 點</small></div><div><button class="secondary" onclick="rejectWish('${w.id}')">略過</button><button class="primary" ${enough?'':'disabled'} onclick="approveWish('${w.id}')">套用願望</button></div></article>`}).join(''):'<p class="pool-hint">目前還沒有待處理願望。</p>'}
let lastAdminEtag='';
async function adminFetch(url,options={}){if(!navigator.onLine)throw new Error('offline');return fetch(url,options)}
async function refreshWishes(){if(!navigator.onLine)return;try{const response=await fetch('/api/live-bundle',{cache:'no-cache'});if(!response.ok)return;const etag=response.headers.get('ETag')||'';if(etag&&etag===lastAdminEtag)return;lastAdminEtag=etag;wishItems=(await response.json()).wishes||[];renderWishPool()}catch(error){}}
async function approveWish(id){const wish=wishItems.find(w=>w.id===id),p=state.players.find(p=>p.name===wish?.playerName);if(!wish||!p)return;if(p.wishPoints<wish.cost)return toast(`${p.name} 的許願點不足`);const combination=buildWishSuggestion(wish);if(!combination)return toast('目前到場名單無法完成這個願望，請稍後再試');if(suggestionHasBlockedPair(combination.map(p=>p.id)))return toast('願望組合碰到拒絕搭檔設定，請先調整名單');if(!suggestionRespectsBindings(combination))return toast('願望組合會拆開綁定球友，請稍後再試');p.wishPoints-=wish.cost;state.arrangementMode='auto';state.matchTypeMode=wish.type==='mixed'?'mixed':'any';$('#match-type-mode').value=state.matchTypeMode;state.funMode=wish.type==='boss'?'boss':'';state.suggestion=combination.map(p=>p.id);await adminFetch('/api/wishes/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'fulfilled'})});render();refreshWishes();toast(`${p.name} 的「${WISH_LABELS[wish.type]}」已套用，扣除 ${wish.cost} 點`);$('#next-up-panel').scrollIntoView({behavior:'smooth',block:'center'})}
async function rejectWish(id){await adminFetch('/api/wishes/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'rejected'})});refreshWishes();toast('願望已略過')}
let pendingLineImport=null,manualSessionSelections=new Map();
function normalizeMemberKey(name){return String(name||'').trim().toLocaleLowerCase('zh-TW')}
function parseLineNote(text){
  const lines=String(text||'').replace(/\r/g,'').split('\n').map(line=>line.trim()).filter(Boolean),dateMatch=String(text||'').match(/(\d{1,2})\s*\/\s*(\d{1,2})/),weekdayMatch=String(text||'').match(/[（(]\s*(週[一二三四五六日天])\s*[）)]/);
  if(!dateMatch)throw new Error('找不到場次日期，請保留例如「8/12（週三）」的標題');
  let section='',order=0;const entries=[];
  for(const line of lines){
    if(/^B\s*時段/i.test(line)){section='B';continue}if(/^C\s*時段/i.test(line)){section='C';continue}
    if(!section)continue;const match=line.match(/^(\d+)\s*[.．、]?\s*(.+)$/);if(!match)continue;
    let rawName=match[2].trim();if(!rawName||rawName==='🈵')continue;
    const combined=/B\s*\+\s*C/i.test(rawName),female=/[（(]\s*F\s*[）)]\s*$/i.test(rawName);
    const name=rawName.replace(/[（(]+\s*B\s*\+\s*C\s*[)）]*/ig,'').replace(/[（(]\s*F\s*[）)]\s*$/ig,'').replace(/[()（）]/g,'').trim();
    if(name)entries.push({name,session:combined?'B+C':section,gender:female?'女':'',order:order++});
  }
  const merged=new Map();entries.forEach(entry=>{const key=normalizeMemberKey(entry.name),previous=merged.get(key);if(!previous)merged.set(key,entry);else{previous.session=previous.session!==entry.session?'B+C':previous.session;if(entry.gender)previous.gender=entry.gender}});
  const roster=[...merged.values()].sort((a,b)=>a.order-b.order),bCount=roster.filter(p=>p.session==='B'||p.session==='B+C').length,cCount=roster.filter(p=>p.session==='C'||p.session==='B+C').length;
  if(!bCount&&!cCount)throw new Error('找不到 B／C 時段的編號名單');
  const year=new Date().getFullYear(),month=+dateMatch[1],day=+dateMatch[2],iso=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
  const titleLine=lines.find(line=>line.includes('開打'))||'',venueLine=lines.find(line=>/[～~].*每週/.test(line))||'',shuttleLine=lines.find(line=>/使用羽球\s*[:：]/.test(line))||'';
  const eventName=titleLine.replace(/^.*?\d{1,2}\s*\/\s*\d{1,2}\s*[（(].*?[）)]\s*/,'').replace(/開打囉.*$/,'').trim()||state.eventName;
  return{date:iso,dateLabel:`${month}/${day}${weekdayMatch?` ${weekdayMatch[1]}`:''}`,eventName,venue:venueLine.split(/[～~]/)[0].trim()||state.venue,shuttle:shuttleLine.replace(/^.*?使用羽球\s*[:：]\s*/,'').trim()||state.shuttle,roster,bCount,cCount,uniqueCount:roster.length}
}
function showLineNoteImport(){pendingLineImport=null;openModal(`<p class="eyebrow">LINE NOTE IMPORT</p><h2>匯入 LINE 記事本</h2><p class="sub">貼上後可直接建立；「解析預覽」僅供確認人數。既有成員會保留等級、動態積分、性別與搭檔偏好。</p><label class="line-note-field">貼上記事本全文<textarea id="line-note-input" placeholder="從 LINE 記事本複製後貼在這裡"></textarea></label><div id="line-import-preview" class="line-import-preview"><span>可直接建立，系統會自動解析與驗證</span></div><div class="modal-actions"><button class="secondary" data-close>取消</button><button class="secondary" onclick="previewLineNote()">解析預覽（選用）</button><button class="primary" id="confirm-line-import" onclick="confirmLineImport()">建立新場次</button></div>`)}
function previewLineNote(){try{pendingLineImport=parseLineNote($('#line-note-input').value);const known=new Set(state.players.map(p=>normalizeMemberKey(p.name))),newCount=pendingLineImport.roster.filter(p=>!known.has(normalizeMemberKey(p.name))).length;$('#line-import-preview').innerHTML=`<strong>${safeHtml(pendingLineImport.dateLabel)} · ${safeHtml(pendingLineImport.eventName)}</strong><div><span>B 時段 <b>${pendingLineImport.bCount}</b> 人</span><span>C 時段 <b>${pendingLineImport.cCount}</b> 人</span><span>不重複 <b>${pendingLineImport.uniqueCount}</b> 人</span><span>新成員 <b>${newCount}</b> 人</span></div><small>${safeHtml(pendingLineImport.venue)} · ${safeHtml(pendingLineImport.shuttle)}</small>`;return true}catch(error){pendingLineImport=null;$('#line-import-preview').innerHTML=`<span class="import-error">${safeHtml(error.message)}</span>`;return false}}
function resetPlayerForSession(p,session){p.session=session;p.status='waiting';p.paid=false;p.games=0;p.wait=0;p.winStreak=0;p.availableFrom=session==='C'?'20:30':'18:00';p.availableUntil=session==='B'?'20:30':'22:30';p.targetGames=session==='B+C'?9:5}
function confirmLineImport(){
  if(!previewLineNote())return;const importData=pendingLineImport,byName=new Map(state.players.map(p=>[normalizeMemberKey(p.name),p])),ids=[];let nextId=Math.max(0,...state.players.map(p=>Number(p.id)||0))+1,newCount=0;
  state.players.forEach(p=>{p.status='absent';p.session='';p.paid=false;p.games=0;p.wait=0;p.winStreak=0});
  importData.roster.forEach((entry,index)=>{let p=byName.get(normalizeMemberKey(entry.name));if(!p){p=seededProfile({name:entry.name,session:entry.session},state.players.length+index);p.id=nextId++;p.voiceAliases=DEFAULT_VOICE_ALIASES[p.name]||[];p.preferredPartnerIds=[];p.blockedPartnerIds=[];state.players.push(p);byName.set(normalizeMemberKey(entry.name),p);newCount++}if(entry.gender)p.gender=entry.gender;resetPlayerForSession(p,entry.session);ids.push(p.id)});
  state.rosterIds=[...new Set(ids)];state.sessionDate=importData.date;state.sessionDateLabel=importData.dateLabel;state.eventName=importData.eventName;state.venue=importData.venue;state.shuttle=importData.shuttle;state.courts=[1,2,3].map(id=>({id,status:'idle',players:[]}));state.history=[];state.suggestion=[];state.simulation=null;state.finished=0;state.startedAt=Date.now();state.pool='waiting';state.paymentReminderOpen=false;state.manualSelectedPlayerId=null;pendingLineImport=null;closeModal();render();activateView('courts');toast(`${importData.dateLabel} 已匯入 ${ids.length} 位球友（新增 ${newCount} 位成員）`)
}
function formatSessionDateLabel(value){if(!value)return'';const [year,month,day]=value.split('-').map(Number),week='日一二三四五六'[new Date(year,month-1,day).getDay()];return`${month}/${day} 週${week}`}
function setCreateMethod(method){const manual=method==='manual';$('#create-method-line').classList.toggle('active',!manual);$('#create-method-manual').classList.toggle('active',manual);$('#create-line-panel').hidden=manual;$('#create-manual-panel').hidden=!manual;if(manual)prepareManualSessionForm()}
function prepareManualSessionForm(){const date=$('#manual-session-date');if(!date.value){date.value=state.sessionDate||new Date().toLocaleDateString('sv-SE');$('#manual-event-name').value=state.eventName||'';$('#manual-venue').value=state.venue||'';$('#manual-shuttle').value=state.shuttle||''}renderManualRoster()}
function renderManualRoster(){
  const grid=$('#manual-roster-grid');if(!grid)return;const query=($('#manual-member-search')?.value||'').trim().toLowerCase(),members=state.players.filter(p=>p.name.toLowerCase().includes(query)).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW'));
  grid.innerHTML=members.map(p=>{const selected=manualSessionSelections.has(p.id),slot=manualSessionSelections.get(p.id)||'B';return`<div class="manual-member-option ${selected?'selected':''}" role="button" tabindex="0" onclick="toggleManualMember(${p.id})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleManualMember(${p.id})}"><span><strong>${safeHtml(p.name)}</strong><small>${p.gender} · Lv.${p.signupLevel} · ${p.rating} 分</small></span><i class="select-mark">${selected?'✓':'＋'}</i>${selected?`<select class="manual-member-slot" aria-label="${safeHtml(p.name)}參加時段" onclick="event.stopPropagation()" onkeydown="event.stopPropagation()" onchange="setManualMemberSlot(${p.id},this.value)"><option value="B" ${slot==='B'?'selected':''}>B 時段</option><option value="C" ${slot==='C'?'selected':''}>C 時段</option><option value="B+C" ${slot==='B+C'?'selected':''}>B+C 全時段</option></select>`:''}</div>`}).join('')||'<p class="empty-member-note">找不到符合的永久成員。</p>';
  const values=[...manualSessionSelections.values()],b=values.filter(slot=>slot==='B'||slot==='B+C').length,c=values.filter(slot=>slot==='C'||slot==='B+C').length;$('#manual-roster-summary').textContent=values.length?`已選 ${values.length} 人 · B ${b} 人／C ${c} 人`:'尚未選擇球友';$('#create-manual-session').disabled=!values.length
}
function toggleManualMember(id){manualSessionSelections.has(id)?manualSessionSelections.delete(id):manualSessionSelections.set(id,'B');renderManualRoster()}
function setManualMemberSlot(id,slot){manualSessionSelections.set(id,slot);renderManualRoster()}
function createManualSession(){
  const date=$('#manual-session-date').value,eventName=$('#manual-event-name').value.trim(),venue=$('#manual-venue').value.trim(),shuttle=$('#manual-shuttle').value.trim();if(!date)return toast('請選擇場次日期');if(!eventName)return toast('請輸入團名');if(!venue)return toast('請輸入場地');if(!manualSessionSelections.size)return toast('請至少選擇一位球友');
  state.players.forEach(p=>{p.status='absent';p.session='';p.paid=false;p.games=0;p.wait=0;p.winStreak=0});manualSessionSelections.forEach((slot,id)=>{const p=player(id);if(p)resetPlayerForSession(p,slot)});state.rosterIds=[...manualSessionSelections.keys()];state.sessionDate=date;state.sessionDateLabel=formatSessionDateLabel(date);state.eventName=eventName;state.venue=venue;state.shuttle=shuttle||state.shuttle;state.courts=[1,2,3].map(id=>({id,status:'idle',players:[]}));state.history=[];state.suggestion=[];state.simulation=null;state.finished=0;state.startedAt=Date.now();state.pool='waiting';state.paymentReminderOpen=false;state.manualSelectedPlayerId=null;const count=state.rosterIds.length;manualSessionSelections=new Map();render();activateView('courts');toast(`${state.sessionDateLabel} 場次已建立，共 ${count} 位球友`)
}
function showAddSessionPlayer(){
  const available=state.players.filter(p=>!isRosterPlayer(p)).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW'));
  openModal(`<p class="eyebrow">ADD TO SESSION</p><h2>加入本場球友</h2><p class="sub">從永久成員中選取，或建立一位新成員；只會影響目前場次名單。</p>${available.length?`<div class="form-grid"><label class="full">既有成員<select id="session-member-id">${available.map(p=>`<option value="${p.id}">${safeHtml(p.name)} · Lv.${p.signupLevel} · ${p.rating} 分</option>`).join('')}</select></label><label class="full">參加時段<select id="session-member-slot"><option value="B">B · 18:00–20:30</option><option value="C">C · 20:30–22:30</option><option value="B+C">B+C · 全時段</option></select></label></div>`:'<p class="empty-member-note">所有永久成員都已在本場名單中。</p>'}<div class="modal-actions spread"><button class="secondary" onclick="addPerson(true)">＋ 建立新成員</button><span></span><button class="secondary" data-close>取消</button>${available.length?'<button class="primary" onclick="addExistingToSession()">加入本場</button>':''}</div>`)
}
function addExistingToSession(){const p=state.players.find(p=>p.id===+$('#session-member-id').value),session=$('#session-member-slot').value;if(!p)return toast('請選擇成員');resetPlayerForSession(p,session);state.rosterIds.push(p.id);state.suggestion=[];state.simulation=null;closeModal();render();toast(`${p.name} 已加入 ${session} 時段`)}
function removePlayerFromSession(id){const p=player(id);if(!p||p.status==='playing')return toast('比賽中的球友不能移出本場');state.rosterIds=state.rosterIds.filter(playerId=>playerId!==id);state.suggestion=state.suggestion.filter(playerId=>playerId!==id);p.status='absent';p.session='';state.manualSelectedPlayerId=null;state.simulation=null;getSuggestion();render();toast(`${p.name} 已移出本場，永久成員資料仍保留`)}
function deleteMember(id){const p=state.players.find(p=>p.id===id);if(!p)return;if(p.status==='playing')return toast('比賽中的球友不能刪除');if(!confirm(`確定永久刪除成員「${p.name}」？此動作也會將他移出本場名單。`))return;state.players=state.players.filter(member=>member.id!==id);state.rosterIds=state.rosterIds.filter(playerId=>playerId!==id);state.suggestion=state.suggestion.filter(playerId=>playerId!==id);state.players.forEach(member=>{member.preferredPartnerIds=(member.preferredPartnerIds||[]).filter(playerId=>playerId!==id);member.blockedPartnerIds=(member.blockedPartnerIds||[]).filter(playerId=>playerId!==id);if(member.boundPartnerId===id){member.boundPartnerId=null;member.boundSession='B+C'}});closeModal();render();toast(`${p.name} 已從永久成員中刪除`)}
function renderMembers(){
  const q=$('#member-search')?.value.toLowerCase()||'',lvl=$('#level-filter')?.value||'all';const list=state.players.filter(p=>p.name.toLowerCase().includes(q)&&(lvl==='all'||p.level===lvl));
  $('#member-table').innerHTML=list.map(p=>`<tr><td><div class="member-name-actions"><button class="member-edit-name" aria-label="編輯 ${p.name}" onclick="showPlayer(${p.id})"><span class="tiny-avatar ${p.gender==='女'?'female-avatar':''}">${p.name[0]}</span><strong>${p.name}</strong><small>${isRosterPlayer(p)?`本場 ${p.session}`:'永久成員'}</small></button><button class="member-delete" aria-label="刪除 ${p.name}" onclick="deleteMember(${p.id})">刪除</button></div></td><td><span class="gender-table ${p.gender==='女'?'female':''}">${p.gender}</span></td><td><b>Lv.${p.signupLevel}</b></td><td><b>${p.rating}</b></td><td><b class="wish-points">✦ ${p.wishPoints}</b></td><td><span class="pill">${p.level}</span></td><td>${p.attendance}%</td><td>${p.wins+p.losses?Math.round(p.wins/(p.wins+p.losses)*100):0}%</td><td>${preferenceNames(p.preferredPartnerIds).join('、')||'—'}</td><td>${preferenceNames(p.blockedPartnerIds).join('、')||'—'}</td><td>${p.boundPartnerId?`<span class="binding-pill">🔗 ${safeHtml(player(p.boundPartnerId)?.name||'—')} · ${p.boundSession}</span>`:'—'}</td><td><span class="time-window">${p.availableFrom}–${p.availableUntil}</span></td><td><b>${isRosterPlayer(p)?`${p.games}/${p.targetGames}`:'—'}</b></td></tr>`).join('');
  const avg=state.players.length?Math.round(state.players.reduce((s,p)=>s+p.rating,0)/state.players.length):0;$('#member-summary').innerHTML=`<div class="summary-card"><span>永久成員</span><strong>${state.players.length}</strong></div><div class="summary-card"><span>本場球友</span><strong>${state.rosterIds.length}</strong></div><div class="summary-card"><span>B／C 時段</span><strong>${sessionRosterCount('B')}／${sessionRosterCount('C')}</strong></div><div class="summary-card"><span>平均實力分</span><strong>${avg}</strong></div>`
}
function renderHistory(){
  $('#history-list').innerHTML=state.history.map(h=>`<div class="history-row"><span class="result">球場 ${h.court}${h.activity?`<small>${funModeName(h.activity)}</small>`:''}</span><div class="teams-side"><strong>${h.a.join(' / ')}</strong><small>${h.winner==='a'?'勝方':'對戰組合'}${h.deltaA!=null?` · 積分 ${h.deltaA>=0?'+':''}${h.deltaA}`:''}</small></div><div class="score">${h.score}${h.manualReview?`<small class="admin-review">團主：${safeHtml(h.manualReview)}</small>`:''}</div><div class="teams-side"><strong>${h.b.join(' / ')}</strong><small>${h.winner==='b'?'勝方':'對戰組合'}${h.deltaB!=null?` · 積分 ${h.deltaB>=0?'+':''}${h.deltaB}`:''}</small></div><time>${h.time}</time></div>`).join('');
  const board=[...state.players].sort((a,b)=>(b.wins-b.losses)-(a.wins-a.losses)).slice(0,6);$('#leaderboard').innerHTML=board.map((p,i)=>`<div class="leader-row"><span>${i+1}</span><strong>${p.name}</strong><strong>${p.wins} 勝</strong></div>`).join('')
}
function chooseBalancedFour(candidates,sessionKey){
  const shortlist=[...candidates].sort((a,b)=>(a.simGames-b.simGames)||(b.simWait-a.simWait)||(a.id-b.id)).slice(0,Math.min(8,candidates.length));
  let best=null;
  for(let a=0;a<shortlist.length-3;a++)for(let b=a+1;b<shortlist.length-2;b++)for(let c=b+1;c<shortlist.length-1;c++)for(let d=c+1;d<shortlist.length;d++){
    const g=[shortlist[a],shortlist[b],shortlist[c],shortlist[d]],options=[[g[0],g[1],g[2],g[3]],[g[0],g[2],g[1],g[3]],[g[0],g[3],g[1],g[2]]];
    options.forEach(o=>{if(!suggestionRespectsBindings(o,sessionKey))return;const diff=Math.abs(o[0].rating+o[1].rating-o[2].rating-o[3].rating),games=o.reduce((s,p)=>s+p.simGames,0),wait=o.reduce((s,p)=>s+p.simWait,0),score=diff+games*18-wait*1.5;if(!best||score<best.score)best={players:o,diff,score}})
  } return best;
}
function runSimulation(){
  const session=simulationSession(),virtual=rosterPlayers().filter(p=>p.status!=='absent'&&isAvailableForSession(p,session)).map(p=>({...p,simGames:0,simWait:p.wait||0})),matches=[],duplicateErrors=[];
  for(let round=1;round<=30;round++){
    virtual.forEach(p=>p.simWait+=4);const pick=chooseBalancedFour(virtual,session.key);if(!pick)break;const ids=pick.players.map(p=>p.id);if(new Set(ids).size!==4)duplicateErrors.push(round);
    const a=pick.players.slice(0,2),b=pick.players.slice(2);pick.players.forEach(p=>{p.simGames++;p.simWait=0});
    matches.push({round,court:(round-1)%session.courts+1,a:a.map(p=>p.name),b:b.map(p=>p.name),aScore:a.reduce((s,p)=>s+p.rating,0),bScore:b.reduce((s,p)=>s+p.rating,0),diff:pick.diff});
  }
  if(virtual.length<4){state.simulation={session:session.key,matches:[],players:virtual.map(p=>({id:p.id,name:p.name,rating:p.rating,games:0})),metrics:{avgDiff:0,maxDiff:0,spread:0,std:0,total:0,players:virtual.length,courts:session.courts},tests:[{name:'可用球友人數',detail:`${session.label}至少需要 4 位可上場球友`,pass:false,value:`${virtual.length} 人`}],at:new Date().toISOString()};renderSimulation();saveState();return toast(`${session.label}可用球友不足 4 人，無法模擬`)}
  const counts=virtual.map(p=>p.simGames),diffs=matches.map(m=>m.diff),avgDiff=Math.round(diffs.reduce((s,n)=>s+n,0)/Math.max(1,diffs.length)),maxDiff=Math.max(0,...diffs),spread=Math.max(...counts)-Math.min(...counts),std=Math.sqrt(counts.reduce((s,n)=>s+Math.pow(n-counts.reduce((a,b)=>a+b,0)/counts.length,2),0)/counts.length),allPlayed=counts.every(n=>n>0);
  const tests=[
    {name:'即時場地限制',detail:`${session.label} 僅使用已租用場地`,pass:matches.every(m=>m.court<=session.courts),value:`${session.courts} 面`},
    {name:'名單完整性',detail:'每場均為 4 位不重複球友',pass:duplicateErrors.length===0,value:duplicateErrors.length?'異常':'30 / 30'},
    {name:'平均實力平衡',detail:'兩隊總分平均差低於 80 分',pass:avgDiff<80,value:`${avgDiff} 分`},
    {name:'極端差距控制',detail:'單場最大實力差低於 160 分',pass:maxDiff<160,value:`${maxDiff} 分`},
    {name:'參與機會覆蓋',detail:'所有在場球友至少上場一次',pass:allPlayed,value:`${counts.filter(n=>n>0).length} / ${counts.length}`},
    {name:'場次公平分布',detail:'最多與最少上場差距不超過 2 場',pass:spread<=2,value:`差 ${spread} 場`}
  ];
  state.simulation={session:session.key,matches,players:virtual.map(p=>({id:p.id,name:p.name,rating:p.rating,games:p.simGames})),metrics:{avgDiff,maxDiff,spread,std:Number(std.toFixed(2)),total:matches.length,players:virtual.length,courts:session.courts},tests,at:new Date().toISOString()};renderSimulation();saveState();toast(`模擬完成：${tests.filter(t=>t.pass).length}/${tests.length} 項通過`)
}
function renderSimulation(){
  const selector=$('#simulation-session');if(selector)selector.value=state.simulationSessionKey;
  const s=state.simulation;if(!s){$('#simulation-metrics').innerHTML='';return}
  const m=s.metrics,pass=s.tests.filter(t=>t.pass).length;$('#simulation-status').textContent=`已完成 ${m.total} 場排點測試`;$('#simulation-time').textContent=new Date(s.at).toLocaleString('zh-TW');
  $('#simulation-metrics').innerHTML=[['時段場地',m.courts||simulationSession().courts,'面',`${s.session||state.simulationSessionKey} 時段限制`],['測試場次',m.total,'場','完整跑完批次排點'],['參與球友',m.players,'人','排除未報到者'],['平均實力差',m.avgDiff,'分','越低代表越均衡'],['最大實力差',m.maxDiff,'分','檢查極端組合'],['場次標準差',m.std,'','越低代表越公平']].map(([label,value,unit,note],i)=>`<div class="metric-card ${i>2?'good':''}"><span>${label}</span><strong>${value}<small style="display:inline"> ${unit}</small></strong><small>${note}</small></div>`).join('');
  $('#test-score').textContent=`${pass} / ${s.tests.length} 通過`;$('#test-results').innerHTML=s.tests.map(t=>`<div class="test-row"><span class="test-icon ${t.pass?'':'fail'}">${t.pass?'✓':'!'}</span><span><strong>${t.name}</strong><small>${t.detail}</small></span><b>${t.value}</b></div>`).join('');
  const max=Math.max(...s.players.map(p=>p.games));$('#participation-chart').innerHTML=[...s.players].sort((a,b)=>b.games-a.games||b.rating-a.rating).map(p=>`<div class="chart-row"><span>${p.name}</span><div class="chart-bar"><i style="width:${p.games/max*100}%"></i></div><strong>${p.games}</strong></div>`).join('');
  $('#simulation-table').innerHTML=s.matches.map(x=>`<tr><td>#${String(x.round).padStart(2,'0')} · ${x.court||1} 場</td><td><b>${x.a.join(' / ')}</b></td><td>${x.aScore}</td><td><b>${x.b.join(' / ')}</b></td><td>${x.bScore}</td><td>${x.diff}</td><td><span class="quality-pill ${x.diff>=100?'warn':''}">${x.diff<60?'極均衡':x.diff<100?'均衡':'具挑戰'}</span></td></tr>`).join('')
}
function setSimulationSession(key){if(!['B','C'].includes(key))return;state.simulationSessionKey=key;state.simulation=null;runSimulation()}
function matchReview(match){if(match.manualReview)return match.manualReview;const [a,b]=String(match.score||'0–0').split(/[–-]/).map(Number),margin=Math.abs(a-b);if(match.activity==='boss')return '勇者挑戰魔王，氣氛拉滿！';if(margin<=2)return '激戰到最後一分，精彩拉鋸！';if(margin>=10)return '火力全開，強勢拿下！';return '攻守有來有往，漂亮對決！'}
function publicStats(){const scores=new Map();state.history.forEach(match=>{const [aScore,bScore]=String(match.score).split(/[–-]/).map(Number);[...match.a,...match.b].forEach(name=>{if(!scores.has(name))scores.set(name,{name,wins:0,pointsFor:0,pointsAgainst:0,diff:0})});match.a.forEach(name=>{const item=scores.get(name);item.pointsFor+=aScore;item.pointsAgainst+=bScore;if(match.winner==='a')item.wins++});match.b.forEach(name=>{const item=scores.get(name);item.pointsFor+=bScore;item.pointsAgainst+=aScore;if(match.winner==='b')item.wins++})});return [...scores.values()].map(item=>({...item,diff:item.pointsFor-item.pointsAgainst})).sort((a,b)=>b.wins-a.wins||b.diff-a.diff||b.pointsFor-a.pointsFor)}
function buildPublicSnapshot(){const session=activeSession(),suggested=state.suggestion.map(player).filter(Boolean);return{updatedAt:Date.now(),event:{name:state.eventName,date:state.sessionDateLabel,venue:state.venue},session:{key:session.key,label:session.label,courts:session.courts},courts:activeCourts().map(c=>({id:c.id,status:c.status,minutes:c.start?Math.floor((Date.now()-c.start)/60000):0,activity:funModeName(c.funMode),matchType:c.matchType||matchTypeFor(c.players.map(player)),a:c.players.slice(0,2).map(id=>player(id)?.name).filter(Boolean),b:c.players.slice(2,4).map(id=>player(id)?.name).filter(Boolean)})),nextUp:suggested.length===4?{a:suggested.slice(0,2).map(p=>p.name),b:suggested.slice(2,4).map(p=>p.name),matchType:matchTypeFor(suggested),diff:Math.abs(suggested[0].rating+suggested[1].rating-suggested[2].rating-suggested[3].rating)}:null,recent:state.history.slice(0,12).map(match=>({id:match.id,court:match.court,a:match.a,b:match.b,score:match.score,time:match.time,activity:funModeName(match.activity),matchType:match.matchType||'自由雙打',review:matchReview(match),customReview:Boolean(match.manualReview),deltaA:match.deltaA??null,deltaB:match.deltaB??null})),stats:publicStats(),players:rosterPlayers().map(p=>({name:p.name,gender:p.gender,rating:p.rating,games:p.games,targetGames:p.targetGames,wins:p.wins,losses:p.losses,session:p.session,status:p.status})).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW')),roster:rosterPlayers().filter(p=>p.status!=='absent'&&isAvailableNow(p)).map(p=>({name:p.name,gender:p.gender,wishPoints:p.wishPoints})).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW'))}}
let publishTimer,lastPublishedSignature='';
function publishLiveState(){if(applyingRemoteState||!navigator.onLine)return;clearTimeout(publishTimer);publishTimer=setTimeout(()=>{const snapshot=buildPublicSnapshot();const {updatedAt,...comparable}=snapshot;const signature=JSON.stringify(comparable);if(signature===lastPublishedSignature)return;lastPublishedSignature=signature;adminFetch('/api/live-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)}).catch(()=>{})},1500)}
async function showLiveBoard(){const url=`${location.origin}/live.html`;openModal(`<p class="eyebrow">PLAYER LIVE BOARD</p><h2>球友即時看板</h2><p class="sub">把下方網址或 QR 分享給球友即可開啟。頁面只公開姓名、比分、趣味數據與留言。</p><div class="share-link"><input id="player-live-url" value="${url}" readonly><button class="secondary" onclick="copyLiveBoardLink()">複製</button></div><div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="window.open('${url}','_blank')">開啟看板</button></div>`)}
async function copyLiveBoardLink(){const input=$('#player-live-url');try{await navigator.clipboard.writeText(input.value);toast('球友看板網址已複製')}catch(error){input.select();document.execCommand('copy');toast('球友看板網址已複製')}}
function render(){renderSidebar();renderCourts();renderArrangementMode();renderSuggestion();renderPool();renderFunStatus();renderWishPool();renderMembers();renderHistory();renderSimulation();saveState();publishLiveState()}
function renderElapsed(){const seconds=Math.max(0,Math.floor((Date.now()-state.startedAt)/1000)),h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#elapsed').textContent=`${h}:${m}:${s}`}
function assignToCourt(id){const session=activeSession(),suggested=state.suggestion.map(player);if(id>session.courts)return toast(`${session.label}僅開放 ${session.courts} 面場地`);if(state.suggestion.length<4)return toast('備戰區人數不足');if(new Set(state.suggestion).size!==4)return toast('候選名單有重複球友，請重新調整');if(state.suggestion.some(id=>!canJoinSuggestion(player(id))))return toast('候選名單包含目前不可上場的球友');if(!suggestionMatchesMode(suggested))return toast('目前組合不符合所選的雙打模式');if(suggestionHasBlockedPair(state.suggestion))return toast('候選名單包含拒絕搭檔組合');if(!suggestionRespectsBindings(suggested))return toast('候選名單拆開了綁定球友，無法安排上場');const c=state.courts.find(c=>c.id===id);if(!c)return toast('找不到可用場地');c.players=[...state.suggestion];c.status='playing';c.start=Date.now();c.funMode=state.funMode||'';c.matchType=matchTypeFor(suggested);state.suggestion.forEach(id=>{const p=player(id);p.status='playing';p.wait=0});const names=state.suggestion.map(id=>player(id).name).join('、');state.suggestion=[];state.funMode='';state.manualSelectedPlayerId=null;getSuggestion();render();toast(`已安排${c.matchType}至球場 ${id}`);if(state.sound&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`請 ${names} 到第 ${id} 場上場`))}}
function finishCourt(id){const c=state.courts.find(c=>c.id===id),ps=c.players.map(player),aRating=ps[0].rating+ps[1].rating,bRating=ps[2].rating+ps[3].rating;openModal(`<p class="eyebrow">RECORD RESULT</p><h2>球場 ${id} · 記錄勝負</h2><p class="sub">完成後球友會回到備戰區，動態積分會依雙方強度使用 Elo 公式更新。</p><div class="result-picker"><div class="result-team"><label>${ps[0].name} / ${ps[1].name}<br>合計 ${aRating}</label><input id="score-a" type="number" value="21" min="0" max="30"></div><b>—</b><div class="result-team"><label>${ps[2].name} / ${ps[3].name}<br>合計 ${bRating}</label><input id="score-b" type="number" value="17" min="0" max="30"></div></div><label class="match-review-input">團主單場評語 <small>選填；留空時由系統依比分產生</small><textarea id="match-review" maxlength="80" placeholder="例如：多拍來回很精彩，兩隊防守都很穩！"></textarea></label><div class="modal-actions"><button class="secondary" data-close>取消</button><button class="primary" onclick="confirmFinish(${id})">完成記錄</button></div>`)}
function awardWishPoints(ps,awin,aTeam,bTeam,deltaA,deltaB){const underdogWon=awin?bTeam-aTeam>=200:aTeam-bTeam>=200;let awarded=0;ps.forEach((p,i)=>{const won=(i<2)===awin,delta=i<2?deltaA:deltaB;if(!won){p.winStreak=0;return}p.winStreak=(p.winStreak||0)+1;let points=1;if(p.winStreak%3===0)points+=2;if(underdogWon)points+=2;p.ratingGainBank=(p.ratingGainBank||0)+Math.max(0,delta);const converted=Math.floor(p.ratingGainBank/25);p.ratingGainBank%=25;points+=converted;p.wishPoints=(p.wishPoints||0)+points;awarded+=points});return{awarded,underdogWon}}
function confirmFinish(id){
  const c=state.courts.find(c=>c.id===id),ps=c.players.map(player),a=+$(`#score-a`).value,b=+$(`#score-b`).value,manualReview=$('#match-review').value.trim().slice(0,80);
  if(a===b)return toast('請輸入有勝負的比分');
  const awin=a>b,aTeam=ps[0].rating+ps[1].rating,bTeam=ps[2].rating+ps[3].rating,expectedA=1/(1+Math.pow(10,(bTeam-aTeam)/800)),k=24,deltaA=Math.round(k*((awin?1:0)-expectedA)),deltaB=-deltaA;
  const wishAward=awardWishPoints(ps,awin,aTeam,bTeam,deltaA,deltaB);
  ps.forEach((p,i)=>{p.status=p.isBoss?'boss':'waiting';p.games++;p.wait=0;const won=(i<2)===awin;if(won)p.wins++;else p.losses++;p.rating=Math.max(100,p.rating+(i<2?deltaA:deltaB))});
  state.history.unshift({id:globalThis.crypto?.randomUUID?.()||`match-${Date.now()}`,court:id,a:[ps[0].name,ps[1].name],b:[ps[2].name,ps[3].name],score:`${a}–${b}`,time:new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}),winner:awin?'a':'b',deltaA,deltaB,activity:c.funMode||'',matchType:c.matchType||matchTypeFor(ps),manualReview,wishPointsAwarded:wishAward.awarded});c.status='idle';c.players=[];c.funMode='';c.matchType='';state.finished++;state.suggestion=[];getSuggestion();closeModal();render();toast(`比分已發布，勝方共獲得 ${wishAward.awarded} 許願點${wishAward.underdogWon?'（含越級成功獎勵）':''}`);if($('#auto-setting').checked)setTimeout(()=>assignToCourt(id),500)
}
function showCourt(id){const c=state.courts.find(c=>c.id===id),ps=c.players.map(player);openModal(`<p class="eyebrow">COURT ${id}</p><h2>場上球友</h2><p class="sub">比賽已進行 ${Math.floor((Date.now()-c.start)/60000)} 分鐘</p>${ps.map((p,i)=>`<div class="leader-row"><span>${i<2?'A':'B'}</span><strong>${p.name}</strong><strong>${p.rating} 分</strong></div>`).join('')}<div class="modal-actions"><button class="secondary" data-close>關閉</button><button class="primary" onclick="closeModal();finishCourt(${id})">結束比賽</button></div>`)}
function partnerPicker(p,kind){const chosen=kind==='preferred'?p.preferredPartnerIds:p.blockedPartnerIds;return state.players.filter(x=>x.id!==p.id).map(x=>`<label class="partner-option"><input type="checkbox" data-partner-kind="${kind}" value="${x.id}" ${chosen.includes(x.id)?'checked':''}><span>${x.name}</span></label>`).join('')}
function bindingPartnerOptions(p){return `<option value="">不綁定</option>${state.players.filter(x=>x.id!==p.id).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW')).map(x=>`<option value="${x.id}" ${p.boundPartnerId===x.id?'selected':''}>${safeHtml(x.name)} · Lv.${x.signupLevel}</option>`).join('')}`}
function showPlayer(id){const p=player(id);openModal(`<p class="eyebrow">PLAYER PROFILE</p><h2>${p.name}</h2><p class="sub">綁定出場是強制規則；適用時段內兩人會固定同隊、同場上場。</p><div class="form-grid"><label>性別<select id="edit-gender"><option value="男" ${p.gender==='男'?'selected':''}>男</option><option value="女" ${p.gender==='女'?'selected':''}>女</option></select></label><label>許願點數<input id="edit-wish-points" type="number" min="0" value="${p.wishPoints}"></label><label class="full">語音別名 <small>以逗號分隔，例如：哈利、阿里</small><input id="edit-voice-aliases" value="${safeHtml((p.voiceAliases||[]).join('、'))}" placeholder="常被辨識成的同音字"></label><label>報名等級<input id="edit-signup-level" type="number" min="1" max="15" step="0.5" value="${p.signupLevel}"></label><label>動態積分<input id="edit-rating" type="number" value="${p.rating}"></label><label>程度標籤<select id="edit-level"><option ${p.level==='進階'?'selected':''}>進階</option><option ${p.level==='中階'?'selected':''}>中階</option><option ${p.level==='初階'?'selected':''}>初階</option></select></label><label>已打場數<input id="edit-games" type="number" value="${p.games}"></label><label>可上場時間<input id="edit-available-from" type="time" value="${p.availableFrom}"></label><label>最晚離場時間<input id="edit-available-until" type="time" value="${p.availableUntil}"></label><label>今晚目標場數<input id="edit-target-games" type="number" min="1" max="20" value="${p.targetGames}"></label><label>目前狀態<select id="edit-status"><option value="waiting" ${p.status==='waiting'?'selected':''}>備戰</option><option value="resting" ${p.status==='resting'?'selected':''}>休息</option><option value="absent" ${p.status==='absent'?'selected':''}>未報到</option></select></label><fieldset class="binding-field full"><legend>🔗 綁定出場 <small>雙方固定同隊、同場上場</small></legend><div class="binding-controls"><label>綁定球友<select id="edit-bound-partner">${bindingPartnerOptions(p)}</select></label><label>適用時段<select id="edit-bound-session"><option value="B" ${p.boundSession==='B'?'selected':''}>B 時段</option><option value="C" ${p.boundSession==='C'?'selected':''}>C 時段</option><option value="B+C" ${p.boundSession==='B+C'?'selected':''}>B+C 全時段</option></select></label></div><p>若任一人不在備戰狀態，另一人也不會被單獨排入候選對戰。</p></fieldset><fieldset class="preference-field full"><legend>偏好搭檔 <small>排點時優先同隊，可複選</small></legend><div class="partner-picker">${partnerPicker(p,'preferred')}</div></fieldset><fieldset class="preference-field full danger"><legend>拒絕搭檔 <small>不會被安排在同一隊，可複選</small></legend><div class="partner-picker">${partnerPicker(p,'blocked')}</div></fieldset></div><div class="schedule-explain"><b>語音辨識提示</b><span>系統會用姓名及語音別名比對目前名單，不會把別名顯示給球友。</span></div><div class="modal-actions"><button class="secondary" onclick="resetRatingFromLevel()">依等級重設積分</button><button class="secondary" data-close>取消</button><button class="primary" onclick="savePlayer(${id})">儲存調整</button></div>`)}
function resetRatingFromLevel(){const level=+$('#edit-signup-level').value;if(level>0){$('#edit-rating').value=Math.round(level*100);toast(`已重設為 ${Math.round(level*100)} 分，儲存後生效`)}}
function detachBinding(p){if(!p)return;const mate=state.players.find(x=>x.id===p.boundPartnerId);p.boundPartnerId=null;p.boundSession='B+C';if(mate?.boundPartnerId===p.id){mate.boundPartnerId=null;mate.boundSession='B+C'}}
function setBinding(p,mateId,session){detachBinding(p);if(!mateId)return;const mate=state.players.find(x=>x.id===mateId);if(!mate)return;detachBinding(mate);p.boundPartnerId=mate.id;mate.boundPartnerId=p.id;p.boundSession=session;mate.boundSession=session}
function savePlayer(id){const p=player(id),signupLevel=+$('#edit-signup-level').value,from=$('#edit-available-from').value,until=$('#edit-available-until').value,preferred=$$('[data-partner-kind="preferred"]:checked').map(x=>+x.value),blocked=$$('[data-partner-kind="blocked"]:checked').map(x=>+x.value),boundId=+$('#edit-bound-partner').value||null,boundSession=$('#edit-bound-session').value,mate=boundId?state.players.find(x=>x.id===boundId):null;if(!signupLevel||signupLevel<1||signupLevel>15)return toast('報名等級請輸入 1–15');if(!from||!until||timeToMinutes(from)>=timeToMinutes(until))return toast('可上場開始時間必須早於離場時間');if(preferred.some(id=>blocked.includes(id)))return toast('同一球友不能同時設為偏好與拒絕搭檔');if(boundId&&(blocked.includes(boundId)||(mate?.blockedPartnerIds||[]).includes(p.id)))return toast('綁定球友不能同時設為拒絕搭檔');p.gender=$('#edit-gender').value;p.wishPoints=Math.max(0,+$('#edit-wish-points').value||0);p.voiceAliases=$('#edit-voice-aliases').value.split(/[,，、\n]+/).map(x=>x.trim()).filter(Boolean);p.signupLevel=signupLevel;p.rating=+$('#edit-rating').value;p.level=$('#edit-level').value;p.games=+$('#edit-games').value;p.availableFrom=from;p.availableUntil=until;p.targetGames=Math.max(1,+$('#edit-target-games').value||1);p.preferredPartnerIds=preferred;p.blockedPartnerIds=blocked;p.partner=preferenceNames(preferred)[0]||'—';setBinding(p,boundId,boundSession);if(p.status!=='playing')p.status=$('#edit-status').value;state.suggestion=[];state.simulation=null;closeModal();render();toast(boundId?`${p.name} 已與 ${mate.name} 綁定 ${boundSession} 時段出場`:'球友資料已更新')}
function syncInitialRating(){const level=+$('#new-signup-level').value||0;$('#new-rating').value=Math.round(level*100);$('#initial-rating-preview').textContent=`Lv.${level} × 100 = ${Math.round(level*100)} 分 · 初始許願點 3 點`}
let addNewMemberToSession=false;
function addPerson(toCurrentSession=false){addNewMemberToSession=Boolean(toCurrentSession);openModal(`<p class="eyebrow">NEW PLAYER</p><h2>${addNewMemberToSession?'建立並加入本場':'新增永久成員'}</h2><p class="sub">輸入性別與報名等級後，初始動態積分為等級 × 100。</p><div class="form-grid"><label class="full">暱稱<input id="new-name" placeholder="例如：小羽"></label><label>性別<select id="new-gender"><option value="男">男</option><option value="女">女</option></select></label><label>報名等級<input id="new-signup-level" type="number" min="1" max="15" step="0.5" value="7" oninput="syncInitialRating()"></label><label>初始動態積分<input id="new-rating" type="number" value="700" readonly></label><label>程度標籤<select id="new-level"><option>中階</option><option>進階</option><option>初階</option></select></label>${addNewMemberToSession?'<label>參加時段<select id="new-session"><option value="B">B · 18:00–20:30</option><option value="C">C · 20:30–22:30</option><option value="B+C">B+C · 全時段</option></select></label>':''}<label>目標場數<input id="new-target-games" type="number" min="1" max="20" value="5"></label><label>可上場時間<input id="new-available-from" type="time" value="18:00"></label><label>最晚離場時間<input id="new-available-until" type="time" value="20:30"></label><p id="initial-rating-preview" class="sub full">Lv.7 × 100 = 700 分 · 初始許願點 3 點</p></div><div class="modal-actions"><button class="secondary" data-close>取消</button><button class="primary" onclick="confirmAdd()">${addNewMemberToSession?'建立並加入本場':'建立永久成員'}</button></div>`)}
function confirmAdd(){const name=$('#new-name').value.trim(),signupLevel=+$('#new-signup-level').value,from=$('#new-available-from').value,until=$('#new-available-until').value;if(!name)return toast('請輸入暱稱');if(state.players.some(p=>normalizeMemberKey(p.name)===normalizeMemberKey(name)))return toast('已有同名成員，請從既有成員加入本場');if(!signupLevel||signupLevel<1||signupLevel>15)return toast('報名等級請輸入 1–15');if(timeToMinutes(from)>=timeToMinutes(until))return toast('可上場開始時間必須早於離場時間');const rating=Math.round(signupLevel*100),session=addNewMemberToSession?$('#new-session').value:'';const p={id:Math.max(0,...state.players.map(p=>Number(p.id)||0))+1,name,session,gender:$('#new-gender').value,signupLevel,rating,level:$('#new-level').value,games:0,wait:0,status:addNewMemberToSession?'waiting':'absent',paid:false,wins:0,losses:0,winStreak:0,wishPoints:3,ratingGainBank:0,attendance:100,partner:'—',voiceAliases:[],preferredPartnerIds:[],blockedPartnerIds:[],boundPartnerId:null,boundSession:'B+C',availableFrom:from,availableUntil:until,targetGames:Math.max(1,+$('#new-target-games').value||1)};state.players.push(p);if(addNewMemberToSession)state.rosterIds.push(p.id);state.suggestion=[];state.simulation=null;closeModal();render();toast(addNewMemberToSession?`${name} 已加入 ${session} 時段`:`${name} 已建立為永久成員`)}

$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));$('#modal').addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeModal()});
function activateView(view){const b=$(`.nav-item[data-view="${view}"]`);if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}-view`).classList.add('active');const titles={courts:'今晚，一起打場好球',create:'建立新的排點場次',members:'讓每位球友都有位置',history:'每場對戰都值得記住',simulation:'用數據驗證每一次排點',settings:'排出公平，也排出樂趣'};$('#page-title').textContent=titles[view];if(view==='create')setCreateMethod('line');history.replaceState(null,'',`?view=${view}`)}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b)activateView(b.dataset.view)});
$('#sidebar-toggle').onclick=toggleSidebar;
$('#open-live-board').onclick=showLiveBoard;
$('#pool-tabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$$('#pool-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.pool=b.dataset.pool;renderPool()});
$('#auto-mode').onclick=()=>setArrangementMode('auto');$('#manual-mode').onclick=()=>setArrangementMode('manual');
$('#voice-listen').onclick=startVoiceCommand;$('#voice-command-form').onsubmit=event=>{event.preventDefault();applyVoiceCommand()};
$('#match-type-mode').value=state.matchTypeMode;$('#match-type-mode').onchange=event=>{state.matchTypeMode=event.target.value;state.suggestion=[];state.funMode='';getSuggestion();renderSuggestion();renderPool();renderFunStatus();saveState();toast(`已切換為 ${event.target.selectedOptions[0].textContent}`)};
$$('[data-fun]').forEach(button=>button.onclick=()=>generateFunMatch(button.dataset.fun));
$('#refresh-match').onclick=()=>{state.funMode='';const result=getSuggestion(true);renderSuggestion();renderPool();renderFunStatus();saveState();if(!result.candidateCount)toast('目前沒有符合條件的四人組合');else if(!result.changed)toast('目前限制下只有這一種合格組合');else toast(`已切換至第 ${result.rank}/${result.candidateCount} 個均衡方案`)};
$('#assign-match').onclick=()=>{const c=activeCourts().find(c=>c.status==='idle');c?assignToCourt(c.id):toast(`${activeSession().label}目前沒有空場`)};$('#auto-arrange').onclick=$('#assign-match').onclick;
$('#add-player').onclick=showAddSessionPlayer;$('#add-member').onclick=()=>addPerson(false);$('#create-import-line').onclick=showLineNoteImport;$('#create-method-line').onclick=()=>setCreateMethod('line');$('#create-method-manual').onclick=()=>setCreateMethod('manual');$('#manual-member-search').oninput=renderManualRoster;$('#create-manual-session').onclick=createManualSession;$('#member-search').oninput=renderMembers;$('#level-filter').onchange=renderMembers;
$('#payment-reminder-toggle').onclick=togglePaymentReminder;
$('#court-session-switch').onchange=event=>switchCourtSession(event.target.value);
$('#sound-toggle').onclick=()=>{state.sound=!state.sound;$('#sound-toggle').textContent=state.sound?'♬':'♩';toast(state.sound?'語音播報已開啟':'語音播報已靜音')};
$('#connectivity-status').onclick=showOfflineGuide;
$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
$$('[data-step]').forEach(b=>b.onclick=()=>{state.gameLimit=Math.max(1,state.gameLimit+ +b.dataset.delta);$('#limit-setting').textContent=state.gameLimit});
$('#save-settings').onclick=()=>toast('排點設定已儲存');$('#edit-suggestion').onclick=()=>setArrangementMode(state.arrangementMode==='manual'?'auto':'manual');
$('#export-history').onclick=()=>{const rows=['場地,A隊,B隊,比分,時間',...state.history.map(h=>`${h.court},${h.a.join('/')},${h.b.join('/')},${h.score},${h.time}`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}));a.download='羽球對戰紀錄.csv';a.click();URL.revokeObjectURL(a.href)};
$('#run-simulation').onclick=runSimulation;$('#export-simulation').onclick=()=>{if(!state.simulation)return toast('請先執行模擬測試');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.simulation,null,2)],{type:'application/json'}));a.download='排點模擬測試報告.json';a.click();URL.revokeObjectURL(a.href)};
$('#simulation-session').onchange=event=>setSimulationSession(event.target.value);
window.addEventListener('resize',()=>fitVisibleNames());
function bootConsole(){registerOfflineApp();setInterval(renderElapsed,1000);setInterval(()=>{rosterPlayers().filter(p=>p.status==='waiting'&&isAvailableNow(p)).forEach(p=>p.wait++);renderCourts();renderSuggestion();renderPool();saveState();publishLiveState()},60000);setInterval(refreshWishes,5000);renderElapsed();render();refreshWishes();if(!state.simulation||state.simulation.session!==state.simulationSessionKey)runSimulation();activateView(new URLSearchParams(location.search).get('view')||'courts')}
bootConsole();
