const $=selector=>document.querySelector(selector);
let lastStateSignature='';
let lastBundleEtag='';
let lastBundle=null;
let selectedMatch={id:'',label:''};
let currentState=null;
let resultsExpanded=false;
let statsExpanded=false;
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
function toast(message){const el=$('#live-toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function relativeTime(value){const seconds=Math.max(0,Math.floor((Date.now()-value)/1000));if(seconds<60)return '剛剛';if(seconds<3600)return `${Math.floor(seconds/60)} 分前`;return new Date(value).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}
function renderState(state){
  currentState=state;
  const rosterByName=new Map((state.roster||[]).map(p=>[p.name,p]));
  const genderBadge=name=>{const gender=rosterByName.get(name)?.gender;return gender?`<em class="live-gender ${gender==='女'?'female':'male'}">${gender}</em>`:''};
  const courtPlayer=name=>`<span class="live-player-name"><b>${escapeHtml(name)}</b>${genderBadge(name)}</span>`;
  const inlinePlayers=(names,delta)=>names.map(name=>`<span class="result-player">${escapeHtml(name)}${genderBadge(name)}</span>`).join('<i>/</i>')+(delta!=null?`<strong class="result-delta ${delta>=0?'gain':'loss'}">${delta>=0?'+':''}${escapeHtml(delta)}</strong>`:'');
  $('#session-label').textContent=`${state.session?.label||'活動'} · ${state.session?.courts||0} 面`;
  $('#updated-at').textContent=state.updatedAt?`最後更新 ${relativeTime(state.updatedAt)}`:'等待管理端發布排點';
  const playing=(state.courts||[]).filter(c=>c.status==='playing');$('#live-court-count').textContent=playing.length;
  $('#live-courts').innerHTML=playing.length?playing.map(c=>`<article class="live-court"><div class="court-heading"><strong>球場 ${c.id}${c.activity?` · ${escapeHtml(c.activity)}`:''}</strong><span>${escapeHtml(c.matchType||'自由雙打')} · ${c.minutes||0} 分鐘</span></div><div class="mobile-court-floor"><div class="mobile-court-lines"></div><span class="mobile-team-label mobile-a">A 隊</span><div class="side top-side">${c.a.map(courtPlayer).join('')}</div><span class="mobile-net">NET</span><span class="mobile-team-label mobile-b">B 隊</span><div class="side bottom-side">${c.b.map(courtPlayer).join('')}</div></div></article>`).join(''):'<div class="empty-live">目前沒有進行中的比賽，下一組正在準備 🏸</div>';
  const recent=state.recent||[],visibleResults=resultsExpanded?recent:recent.slice(0,2);$('#toggle-results').hidden=recent.length<=2;$('#toggle-results').textContent=resultsExpanded?'收合':'展開全部';
  $('#recent-results').innerHTML=visibleResults.length?visibleResults.map(match=>{const label=`球場 ${match.court} · ${match.score} · ${match.a.join('/')} vs ${match.b.join('/')}`;return `<article class="result-card"><div class="result-top"><div class="result-team">${inlinePlayers(match.a,match.deltaA)}</div><div class="result-score">${escapeHtml(match.score)}</div><div class="result-team">${inlinePlayers(match.b,match.deltaB)}</div></div><div class="result-meta"><span>${escapeHtml(match.time)} · 球場 ${match.court} · ${escapeHtml(match.matchType||'自由雙打')}${match.activity?` · ${escapeHtml(match.activity)}`:''}</span><span class="match-review">${match.customReview?'團主評語：':''}${escapeHtml(match.review)}</span></div><button class="match-comment-button" data-match-id="${escapeHtml(match.id)}" data-match-label="${escapeHtml(label)}">💬 針對本場留言</button></article>`}).join(''):'<div class="empty-live">尚未登記比賽結果</div>';
  const stats=state.stats||[],visibleStats=statsExpanded?stats:stats.slice(0,2);$('#toggle-stats').hidden=stats.length<=2;$('#toggle-stats').textContent=statsExpanded?'收合':'展開全部';
  $('#fun-stats').innerHTML=visibleStats.length?visibleStats.map((p,index)=>`<article class="stat-card"><span class="stat-rank">${index+1}</span><strong>${escapeHtml(p.name)}${genderBadge(p.name)}</strong><span><b>${p.wins}</b> 勝 · 得 ${p.pointsFor}／失 ${p.pointsAgainst} · 淨勝 ${p.diff>0?'+':''}${p.diff}</span></article>`).join(''):'<div class="empty-live">完成比賽後會產生趣味排行</div>';
  const select=$('#wish-player'),current=select.value;select.innerHTML='<option value="">我是誰？</option>'+((state.roster||[]).map(p=>`<option value="${escapeHtml(p.name)}">${p.gender==='女'?'♀':'♂'} ${escapeHtml(p.name)} · ${p.wishPoints} 點</option>`).join(''));if([...select.options].some(option=>option.value===current))select.value=current;
}
function renderComments(comments){$('#comments').innerHTML=comments.length?[...comments].reverse().map(comment=>`<article class="comment">${comment.matchLabel?`<button class="comment-match-tag" data-match-id="${escapeHtml(comment.matchId)}" data-match-label="${escapeHtml(comment.matchLabel)}">🏸 ${escapeHtml(comment.matchLabel)}</button>`:''}<div class="comment-head"><strong>${escapeHtml(comment.name)}</strong><time>${relativeTime(comment.createdAt)}</time></div><p>${escapeHtml(comment.message)}</p><div class="reactions">${['👍','🔥','🏸','👏'].map(emoji=>`<button class="reaction" data-id="${comment.id}" data-emoji="${emoji}">${emoji} ${comment.reactions?.[emoji]||''}</button>`).join('')}</div></article>`).join(''):'<div class="empty-live">還沒有留言，來當第一個替大家加油的人！</div>'}
const WISH_LABELS={partner:'指定搭檔',opponent:'指定對手',mixed:'想打混雙',boss:'挑戰魔王'};
function renderWishes(wishes){const visible=wishes.filter(w=>w.status!=='rejected').slice(-12).reverse();$('#public-wishes').innerHTML=visible.length?visible.map(w=>`<article class="public-wish"><span>${w.status==='fulfilled'?'✓ 已實現':'等待中'}</span><strong>${escapeHtml(w.playerName)} · ${WISH_LABELS[w.type]}</strong><small>${w.target?`對象：${escapeHtml(w.target)} · `:''}${w.cost} 點</small></article>`).join(''):'<div class="empty-live">還沒有人許願，累積點數後來試試看！</div>'}
function selectMatchComment(id,label){selectedMatch={id,label};$('#comment-target-label').textContent=label;$('#comment-target').hidden=false;$('#comment-message').placeholder='寫下對這場比賽的看法…';$('#comment-message').focus();$('#comment-form').scrollIntoView({behavior:'smooth',block:'center'})}
function clearMatchComment(){selectedMatch={id:'',label:''};$('#comment-target').hidden=true;$('#comment-message').placeholder='說點什麼…'}
function paintBundle(bundle){const signature=JSON.stringify(bundle.state);if(signature!==lastStateSignature){renderState(bundle.state||{});lastStateSignature=signature}renderComments(bundle.comments||[]);renderWishes(bundle.wishes||[])}
async function refresh(){try{const headers=lastBundleEtag?{'If-None-Match':lastBundleEtag}:undefined;const response=await fetch('/api/live-bundle',{cache:'no-store',headers});if(response.status===304){if(lastBundle)paintBundle(lastBundle)}else{if(!response.ok)throw new Error();lastBundleEtag=response.headers.get('ETag')||'';lastBundle=await response.json();paintBundle(lastBundle)}$('.connection').classList.remove('offline');$('#connection-text').textContent='即時連線'}catch(error){$('.connection').classList.add('offline');$('#connection-text').textContent='重新連線中'}}
$('#comment-form').addEventListener('submit',async event=>{event.preventDefault();const name=$('#comment-name').value.trim(),message=$('#comment-message').value.trim();if(!name||!message)return;localStorage.setItem('badminton-live-name',name);const response=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,message,matchId:selectedMatch.id,matchLabel:selectedMatch.label})});if(response.ok){$('#comment-message').value='';clearMatchComment();toast('留言已送出');refresh()}else toast('留言送出失敗')});
$('#recent-results').addEventListener('click',event=>{const button=event.target.closest('.match-comment-button');if(button)selectMatchComment(button.dataset.matchId,button.dataset.matchLabel)});
$('#comments').addEventListener('click',async event=>{const matchTag=event.target.closest('.comment-match-tag');if(matchTag)return selectMatchComment(matchTag.dataset.matchId,matchTag.dataset.matchLabel);const button=event.target.closest('.reaction');if(!button)return;button.disabled=true;await fetch('/api/reactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:button.dataset.id,emoji:button.dataset.emoji})});refresh()});
$('#clear-comment-target').onclick=clearMatchComment;
$('#toggle-results').onclick=()=>{resultsExpanded=!resultsExpanded;if(currentState)renderState(currentState)};
$('#toggle-stats').onclick=()=>{statsExpanded=!statsExpanded;if(currentState)renderState(currentState)};
document.querySelector('.live-menu').addEventListener('click',event=>{const button=event.target.closest('[data-live-menu]');if(!button)return;document.querySelectorAll('[data-live-menu]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});document.querySelectorAll('[data-live-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.livePanel===button.dataset.liveMenu));window.scrollTo({top:0,behavior:'smooth'})});
$('#wish-form').addEventListener('submit',async event=>{event.preventDefault();const playerName=$('#wish-player').value,type=$('#wish-type').value,target=$('#wish-target').value.trim();const response=await fetch('/api/wishes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerName,type,target})});if(response.ok){$('#wish-target').value='';toast('願望已送到團主許願池');refresh()}else{const result=await response.json().catch(()=>({}));toast(result.error||'願望送出失敗')}});
$('#comment-name').value=localStorage.getItem('badminton-live-name')||'';
refresh();setInterval(refresh,3500);
